# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.flow_definition import FlowDefinition
from ..types.flow_detail_response import FlowDetailResponse
from ..types.flow_version_detail_response import FlowVersionDetailResponse
from ..types.max_call_duration_settings import MaxCallDurationSettings
from ..types.paginated_response import PaginatedResponse
from ..types.publish_flow_response import PublishFlowResponse
from ..types.rollback_response import RollbackResponse
from ..types.user_idle_settings import UserIdleSettings
from ..types.validation_response import ValidationResponse
from .raw_client import AsyncRawFlowsClient, RawFlowsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FlowsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFlowsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFlowsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFlowsClient
        """
        return self._raw_client

    def list_flows(self, *, request_options: typing.Optional[RequestOptions] = None) -> PaginatedResponse:
        """
        GET /api/v1/flows

        Returns lightweight flow list with connected phones.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponse
            Paginated list of flows with connected phone numbers

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.flows.list_flows()
        """
        _response = self._raw_client.list_flows(request_options=request_options)
        return _response.data

    def create_flow(
        self,
        *,
        name: str,
        analysis_instructions: typing.Optional[str] = OMIT,
        analysis_override: typing.Optional[str] = OMIT,
        definition: typing.Optional[FlowDefinition] = OMIT,
        description: typing.Optional[str] = OMIT,
        layout: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        max_call_duration: typing.Optional[MaxCallDurationSettings] = OMIT,
        recording_override: typing.Optional[str] = OMIT,
        user_idle: typing.Optional[UserIdleSettings] = OMIT,
        voicemail_enabled: typing.Optional[bool] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        voicemail_message_prompt: typing.Optional[str] = OMIT,
        voicemail_response_delay_secs: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FlowDetailResponse:
        """
        POST /api/v1/flows

        Definition is optional — omit to create an empty draft for the builder UI,
        or provide it to create a flow with initial content.

        Parameters
        ----------
        name : str
            Display name of the flow (1-255 characters)

        analysis_instructions : typing.Optional[str]
            Custom analysis instructions appended to the base analysis prompt

        analysis_override : typing.Optional[str]
            Call analysis behavior override: "use_account_default", "enabled", or "disabled"

        definition : typing.Optional[FlowDefinition]

        description : typing.Optional[str]
            Description of the flow's purpose (max 1000 characters)

        layout : typing.Optional[typing.Dict[str, typing.Any]]
            Visual builder layout (node positions, viewport). Opaque to the API.
            When present it is stored as-is; when omitted, a default layout is
            generated from the definition.

        max_call_duration : typing.Optional[MaxCallDurationSettings]

        recording_override : typing.Optional[str]
            Recording behavior override: "use_account_default", "enabled", or "disabled"

        user_idle : typing.Optional[UserIdleSettings]

        voicemail_enabled : typing.Optional[bool]
            Enable voicemail detection for this flow (outbound Twilio calls only)

        voicemail_message : typing.Optional[str]
            Static voicemail message spoken verbatim (skips the composer LLM call)

        voicemail_message_prompt : typing.Optional[str]
            Instruction for composing the voicemail message (ignored if message is set)

        voicemail_response_delay_secs : typing.Optional[float]
            Seconds to wait after the callee stops speaking before leaving the message

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlowDetailResponse
            Flow created

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.flows.create_flow(
            name="Appointment Reminder",
        )
        """
        _response = self._raw_client.create_flow(
            name=name,
            analysis_instructions=analysis_instructions,
            analysis_override=analysis_override,
            definition=definition,
            description=description,
            layout=layout,
            max_call_duration=max_call_duration,
            recording_override=recording_override,
            user_idle=user_idle,
            voicemail_enabled=voicemail_enabled,
            voicemail_message=voicemail_message,
            voicemail_message_prompt=voicemail_message_prompt,
            voicemail_response_delay_secs=voicemail_response_delay_secs,
            request_options=request_options,
        )
        return _response.data

    def get_flow(self, flow_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> FlowDetailResponse:
        """
        GET /api/v1/flows/:flowId

        Returns full flow details including definition, layout, and connected phones.

        Parameters
        ----------
        flow_id : str
            Flow ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlowDetailResponse
            Flow details

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.flows.get_flow(
            flow_id="flowId",
        )
        """
        _response = self._raw_client.get_flow(flow_id, request_options=request_options)
        return _response.data

    def update_flow(
        self,
        flow_id: str,
        *,
        analysis_instructions: typing.Optional[str] = OMIT,
        analysis_override: typing.Optional[str] = OMIT,
        definition: typing.Optional[FlowDefinition] = OMIT,
        description: typing.Optional[str] = OMIT,
        layout: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        max_call_duration: typing.Optional[MaxCallDurationSettings] = OMIT,
        name: typing.Optional[str] = OMIT,
        recording_override: typing.Optional[str] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        user_idle: typing.Optional[UserIdleSettings] = OMIT,
        voicemail_enabled: typing.Optional[bool] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        voicemail_message_prompt: typing.Optional[str] = OMIT,
        voicemail_response_delay_secs: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FlowDetailResponse:
        """
        PUT /api/v1/flows/:flowId

        Parameters
        ----------
        flow_id : str
            Flow ID

        analysis_instructions : typing.Optional[str]
            Custom analysis instructions appended to the base analysis prompt

        analysis_override : typing.Optional[str]
            Call analysis behavior override: "use_account_default", "enabled", or "disabled"

        definition : typing.Optional[FlowDefinition]

        description : typing.Optional[str]
            Updated description (max 1000 characters)

        layout : typing.Optional[typing.Dict[str, typing.Any]]
            Visual builder layout. Opaque to the API; stored and returned as-is.

        max_call_duration : typing.Optional[MaxCallDurationSettings]

        name : typing.Optional[str]
            Updated display name (1-255 characters)

        recording_override : typing.Optional[str]
            Recording behavior override: "use_account_default", "enabled", or "disabled"

        tags : typing.Optional[typing.Sequence[str]]
            Updated tags for filtering and organization (max 10)

        user_idle : typing.Optional[UserIdleSettings]

        voicemail_enabled : typing.Optional[bool]
            Enable voicemail detection for this flow (outbound Twilio calls only)

        voicemail_message : typing.Optional[str]
            Static voicemail message spoken verbatim (skips the composer LLM call)

        voicemail_message_prompt : typing.Optional[str]
            Instruction for composing the voicemail message (ignored if message is set)

        voicemail_response_delay_secs : typing.Optional[float]
            Seconds to wait after the callee stops speaking before leaving the message

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlowDetailResponse
            Flow updated

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.flows.update_flow(
            flow_id="flowId",
        )
        """
        _response = self._raw_client.update_flow(
            flow_id,
            analysis_instructions=analysis_instructions,
            analysis_override=analysis_override,
            definition=definition,
            description=description,
            layout=layout,
            max_call_duration=max_call_duration,
            name=name,
            recording_override=recording_override,
            tags=tags,
            user_idle=user_idle,
            voicemail_enabled=voicemail_enabled,
            voicemail_message=voicemail_message,
            voicemail_message_prompt=voicemail_message_prompt,
            voicemail_response_delay_secs=voicemail_response_delay_secs,
            request_options=request_options,
        )
        return _response.data

    def delete_flow(self, flow_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        DELETE /api/v1/flows/:flowId

        Returns 204 No Content on success.

        Parameters
        ----------
        flow_id : str
            Flow ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.flows.delete_flow(
            flow_id="flowId",
        )
        """
        _response = self._raw_client.delete_flow(flow_id, request_options=request_options)
        return _response.data

    def publish_flow(
        self,
        flow_id: str,
        *,
        expected_version: typing.Optional[str] = OMIT,
        notes: typing.Optional[str] = OMIT,
        version: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublishFlowResponse:
        """
        POST /api/v1/flows/:flowId/publish

        Parameters
        ----------
        flow_id : str
            Flow ID

        expected_version : typing.Optional[str]
            Expected current version for optimistic locking (rejects with 409 if stale)

        notes : typing.Optional[str]
            Changelog notes describing what changed in this version (max 1000 characters)

        version : typing.Optional[str]
            Explicit version override in X.Y.Z format (auto-increments patch if omitted)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublishFlowResponse
            Flow published

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.flows.publish_flow(
            flow_id="flowId",
        )
        """
        _response = self._raw_client.publish_flow(
            flow_id, expected_version=expected_version, notes=notes, version=version, request_options=request_options
        )
        return _response.data

    def rollback_flow(
        self, flow_id: str, version: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RollbackResponse:
        """
        POST /api/v1/flows/:flowId/rollback/:version

        Parameters
        ----------
        flow_id : str
            Flow ID

        version : str
            Version to rollback to

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RollbackResponse
            Rollback result

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.flows.rollback_flow(
            flow_id="flowId",
            version="version",
        )
        """
        _response = self._raw_client.rollback_flow(flow_id, version, request_options=request_options)
        return _response.data

    def validate_flow(
        self, flow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ValidationResponse:
        """
        POST /api/v1/flows/:flowId/validate

        Parameters
        ----------
        flow_id : str
            Flow ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValidationResponse
            Validation result

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.flows.validate_flow(
            flow_id="flowId",
        )
        """
        _response = self._raw_client.validate_flow(flow_id, request_options=request_options)
        return _response.data

    def get_flow_version(
        self, flow_id: str, version: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FlowVersionDetailResponse:
        """
        GET /api/v1/flows/:flowId/versions/:version

        Parameters
        ----------
        flow_id : str
            Flow ID

        version : str
            Version string

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlowVersionDetailResponse
            Version details

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.flows.get_flow_version(
            flow_id="flowId",
            version="version",
        )
        """
        _response = self._raw_client.get_flow_version(flow_id, version, request_options=request_options)
        return _response.data


class AsyncFlowsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFlowsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFlowsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFlowsClient
        """
        return self._raw_client

    async def list_flows(self, *, request_options: typing.Optional[RequestOptions] = None) -> PaginatedResponse:
        """
        GET /api/v1/flows

        Returns lightweight flow list with connected phones.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponse
            Paginated list of flows with connected phone numbers

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flows.list_flows()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_flows(request_options=request_options)
        return _response.data

    async def create_flow(
        self,
        *,
        name: str,
        analysis_instructions: typing.Optional[str] = OMIT,
        analysis_override: typing.Optional[str] = OMIT,
        definition: typing.Optional[FlowDefinition] = OMIT,
        description: typing.Optional[str] = OMIT,
        layout: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        max_call_duration: typing.Optional[MaxCallDurationSettings] = OMIT,
        recording_override: typing.Optional[str] = OMIT,
        user_idle: typing.Optional[UserIdleSettings] = OMIT,
        voicemail_enabled: typing.Optional[bool] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        voicemail_message_prompt: typing.Optional[str] = OMIT,
        voicemail_response_delay_secs: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FlowDetailResponse:
        """
        POST /api/v1/flows

        Definition is optional — omit to create an empty draft for the builder UI,
        or provide it to create a flow with initial content.

        Parameters
        ----------
        name : str
            Display name of the flow (1-255 characters)

        analysis_instructions : typing.Optional[str]
            Custom analysis instructions appended to the base analysis prompt

        analysis_override : typing.Optional[str]
            Call analysis behavior override: "use_account_default", "enabled", or "disabled"

        definition : typing.Optional[FlowDefinition]

        description : typing.Optional[str]
            Description of the flow's purpose (max 1000 characters)

        layout : typing.Optional[typing.Dict[str, typing.Any]]
            Visual builder layout (node positions, viewport). Opaque to the API.
            When present it is stored as-is; when omitted, a default layout is
            generated from the definition.

        max_call_duration : typing.Optional[MaxCallDurationSettings]

        recording_override : typing.Optional[str]
            Recording behavior override: "use_account_default", "enabled", or "disabled"

        user_idle : typing.Optional[UserIdleSettings]

        voicemail_enabled : typing.Optional[bool]
            Enable voicemail detection for this flow (outbound Twilio calls only)

        voicemail_message : typing.Optional[str]
            Static voicemail message spoken verbatim (skips the composer LLM call)

        voicemail_message_prompt : typing.Optional[str]
            Instruction for composing the voicemail message (ignored if message is set)

        voicemail_response_delay_secs : typing.Optional[float]
            Seconds to wait after the callee stops speaking before leaving the message

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlowDetailResponse
            Flow created

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flows.create_flow(
                name="Appointment Reminder",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_flow(
            name=name,
            analysis_instructions=analysis_instructions,
            analysis_override=analysis_override,
            definition=definition,
            description=description,
            layout=layout,
            max_call_duration=max_call_duration,
            recording_override=recording_override,
            user_idle=user_idle,
            voicemail_enabled=voicemail_enabled,
            voicemail_message=voicemail_message,
            voicemail_message_prompt=voicemail_message_prompt,
            voicemail_response_delay_secs=voicemail_response_delay_secs,
            request_options=request_options,
        )
        return _response.data

    async def get_flow(
        self, flow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FlowDetailResponse:
        """
        GET /api/v1/flows/:flowId

        Returns full flow details including definition, layout, and connected phones.

        Parameters
        ----------
        flow_id : str
            Flow ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlowDetailResponse
            Flow details

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flows.get_flow(
                flow_id="flowId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_flow(flow_id, request_options=request_options)
        return _response.data

    async def update_flow(
        self,
        flow_id: str,
        *,
        analysis_instructions: typing.Optional[str] = OMIT,
        analysis_override: typing.Optional[str] = OMIT,
        definition: typing.Optional[FlowDefinition] = OMIT,
        description: typing.Optional[str] = OMIT,
        layout: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        max_call_duration: typing.Optional[MaxCallDurationSettings] = OMIT,
        name: typing.Optional[str] = OMIT,
        recording_override: typing.Optional[str] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        user_idle: typing.Optional[UserIdleSettings] = OMIT,
        voicemail_enabled: typing.Optional[bool] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        voicemail_message_prompt: typing.Optional[str] = OMIT,
        voicemail_response_delay_secs: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FlowDetailResponse:
        """
        PUT /api/v1/flows/:flowId

        Parameters
        ----------
        flow_id : str
            Flow ID

        analysis_instructions : typing.Optional[str]
            Custom analysis instructions appended to the base analysis prompt

        analysis_override : typing.Optional[str]
            Call analysis behavior override: "use_account_default", "enabled", or "disabled"

        definition : typing.Optional[FlowDefinition]

        description : typing.Optional[str]
            Updated description (max 1000 characters)

        layout : typing.Optional[typing.Dict[str, typing.Any]]
            Visual builder layout. Opaque to the API; stored and returned as-is.

        max_call_duration : typing.Optional[MaxCallDurationSettings]

        name : typing.Optional[str]
            Updated display name (1-255 characters)

        recording_override : typing.Optional[str]
            Recording behavior override: "use_account_default", "enabled", or "disabled"

        tags : typing.Optional[typing.Sequence[str]]
            Updated tags for filtering and organization (max 10)

        user_idle : typing.Optional[UserIdleSettings]

        voicemail_enabled : typing.Optional[bool]
            Enable voicemail detection for this flow (outbound Twilio calls only)

        voicemail_message : typing.Optional[str]
            Static voicemail message spoken verbatim (skips the composer LLM call)

        voicemail_message_prompt : typing.Optional[str]
            Instruction for composing the voicemail message (ignored if message is set)

        voicemail_response_delay_secs : typing.Optional[float]
            Seconds to wait after the callee stops speaking before leaving the message

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlowDetailResponse
            Flow updated

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flows.update_flow(
                flow_id="flowId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_flow(
            flow_id,
            analysis_instructions=analysis_instructions,
            analysis_override=analysis_override,
            definition=definition,
            description=description,
            layout=layout,
            max_call_duration=max_call_duration,
            name=name,
            recording_override=recording_override,
            tags=tags,
            user_idle=user_idle,
            voicemail_enabled=voicemail_enabled,
            voicemail_message=voicemail_message,
            voicemail_message_prompt=voicemail_message_prompt,
            voicemail_response_delay_secs=voicemail_response_delay_secs,
            request_options=request_options,
        )
        return _response.data

    async def delete_flow(self, flow_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        DELETE /api/v1/flows/:flowId

        Returns 204 No Content on success.

        Parameters
        ----------
        flow_id : str
            Flow ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flows.delete_flow(
                flow_id="flowId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_flow(flow_id, request_options=request_options)
        return _response.data

    async def publish_flow(
        self,
        flow_id: str,
        *,
        expected_version: typing.Optional[str] = OMIT,
        notes: typing.Optional[str] = OMIT,
        version: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublishFlowResponse:
        """
        POST /api/v1/flows/:flowId/publish

        Parameters
        ----------
        flow_id : str
            Flow ID

        expected_version : typing.Optional[str]
            Expected current version for optimistic locking (rejects with 409 if stale)

        notes : typing.Optional[str]
            Changelog notes describing what changed in this version (max 1000 characters)

        version : typing.Optional[str]
            Explicit version override in X.Y.Z format (auto-increments patch if omitted)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublishFlowResponse
            Flow published

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flows.publish_flow(
                flow_id="flowId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.publish_flow(
            flow_id, expected_version=expected_version, notes=notes, version=version, request_options=request_options
        )
        return _response.data

    async def rollback_flow(
        self, flow_id: str, version: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RollbackResponse:
        """
        POST /api/v1/flows/:flowId/rollback/:version

        Parameters
        ----------
        flow_id : str
            Flow ID

        version : str
            Version to rollback to

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RollbackResponse
            Rollback result

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flows.rollback_flow(
                flow_id="flowId",
                version="version",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rollback_flow(flow_id, version, request_options=request_options)
        return _response.data

    async def validate_flow(
        self, flow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ValidationResponse:
        """
        POST /api/v1/flows/:flowId/validate

        Parameters
        ----------
        flow_id : str
            Flow ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValidationResponse
            Validation result

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flows.validate_flow(
                flow_id="flowId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_flow(flow_id, request_options=request_options)
        return _response.data

    async def get_flow_version(
        self, flow_id: str, version: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FlowVersionDetailResponse:
        """
        GET /api/v1/flows/:flowId/versions/:version

        Parameters
        ----------
        flow_id : str
            Flow ID

        version : str
            Version string

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FlowVersionDetailResponse
            Version details

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.flows.get_flow_version(
                flow_id="flowId",
                version="version",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_flow_version(flow_id, version, request_options=request_options)
        return _response.data
