# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.phone_provider_response import PhoneProviderResponse
from .raw_client import AsyncRawPhoneProvidersClient, RawPhoneProvidersClient


class PhoneProvidersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPhoneProvidersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPhoneProvidersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPhoneProvidersClient
        """
        return self._raw_client

    def list_phone_providers(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[PhoneProviderResponse]:
        """
        GET /api/v1/phone/providers

        Parameters
        ----------
        limit : typing.Optional[int]
            Max items to return

        offset : typing.Optional[int]
            Items to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[PhoneProviderResponse]
            List of providers

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.phone_providers.list_phone_providers()
        """
        _response = self._raw_client.list_phone_providers(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    def get_provider(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneProviderResponse:
        """
        GET /api/v1/phone/providers/:id

        Parameters
        ----------
        id : str
            Provider ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneProviderResponse
            Provider details

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.phone_providers.get_provider(
            id="id",
        )
        """
        _response = self._raw_client.get_provider(id, request_options=request_options)
        return _response.data


class AsyncPhoneProvidersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPhoneProvidersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPhoneProvidersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPhoneProvidersClient
        """
        return self._raw_client

    async def list_phone_providers(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[PhoneProviderResponse]:
        """
        GET /api/v1/phone/providers

        Parameters
        ----------
        limit : typing.Optional[int]
            Max items to return

        offset : typing.Optional[int]
            Items to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[PhoneProviderResponse]
            List of providers

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_providers.list_phone_providers()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_phone_providers(
            limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def get_provider(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneProviderResponse:
        """
        GET /api/v1/phone/providers/:id

        Parameters
        ----------
        id : str
            Provider ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneProviderResponse
            Provider details

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_providers.get_provider(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_provider(id, request_options=request_options)
        return _response.data
