# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.schedule_frequency import ScheduleFrequency
from ..types.schedule_list_response import ScheduleListResponse
from ..types.schedule_response import ScheduleResponse
from ..types.schedule_status import ScheduleStatus
from .raw_client import AsyncRawSchedulesClient, RawSchedulesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SchedulesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSchedulesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSchedulesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSchedulesClient
        """
        return self._raw_client

    def list_schedules(
        self,
        *,
        status: typing.Optional[ScheduleStatus] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ScheduleResponse, ScheduleListResponse]:
        """
        Parameters
        ----------
        status : typing.Optional[ScheduleStatus]
            Filter by status

        limit : typing.Optional[int]
            Max items to return

        offset : typing.Optional[int]
            Items to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ScheduleResponse, ScheduleListResponse]
            Schedule list

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        response = client.schedules.list_schedules()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_schedules(
            status=status, limit=limit, offset=offset, request_options=request_options
        )

    def create_schedule(
        self,
        *,
        contact_id: str,
        flow_id: str,
        frequency: ScheduleFrequency,
        from_phone_number: str,
        name: str,
        provider_id: str,
        schedule_time: str,
        cron_expression: typing.Optional[str] = OMIT,
        day_of_month: typing.Optional[int] = OMIT,
        days_of_week: typing.Optional[typing.Sequence[int]] = OMIT,
        end_date: typing.Optional[dt.date] = OMIT,
        max_retries: typing.Optional[int] = OMIT,
        max_runs: typing.Optional[int] = OMIT,
        retry_delay_minutes: typing.Optional[int] = OMIT,
        retry_on_failure: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScheduleResponse:
        """
        Parameters
        ----------
        contact_id : str
            Contact to call on each schedule execution

        flow_id : str
            Flow (conversation script) to use for the call

        frequency : ScheduleFrequency
            How often the schedule should repeat

        from_phone_number : str
            Caller ID phone number in E.164 format

        name : str
            Human-readable name for the schedule

        provider_id : str
            VoIP provider to route the call through

        schedule_time : str
            Time of day to execute in HH:MM or HH:MM:SS format

        cron_expression : typing.Optional[str]
            Custom cron expression, required when frequency is `custom_cron`

        day_of_month : typing.Optional[int]
            Day of month to run on (1-28), used with `monthly` frequency

        days_of_week : typing.Optional[typing.Sequence[int]]
            Days of week to run on (1=Monday through 7=Sunday), used with `weekly` frequency

        end_date : typing.Optional[dt.date]
            Date after which the schedule will not execute

        max_retries : typing.Optional[int]
            Maximum number of retry attempts per execution (0-10)

        max_runs : typing.Optional[int]
            Maximum number of executions before auto-completing

        retry_delay_minutes : typing.Optional[int]
            Minutes to wait before retrying a failed call (1-1440)

        retry_on_failure : typing.Optional[bool]
            Whether to retry the call if it fails

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScheduleResponse
            Schedule created

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.schedules.create_schedule(
            contact_id="550e8400-e29b-41d4-a716-446655440000",
            flow_id="550e8400-e29b-41d4-a716-446655440000",
            frequency="once",
            from_phone_number="+15551234567",
            name="Daily Follow-up Call",
            provider_id="550e8400-e29b-41d4-a716-446655440000",
            schedule_time="09:00",
        )
        """
        _response = self._raw_client.create_schedule(
            contact_id=contact_id,
            flow_id=flow_id,
            frequency=frequency,
            from_phone_number=from_phone_number,
            name=name,
            provider_id=provider_id,
            schedule_time=schedule_time,
            cron_expression=cron_expression,
            day_of_month=day_of_month,
            days_of_week=days_of_week,
            end_date=end_date,
            max_retries=max_retries,
            max_runs=max_runs,
            retry_delay_minutes=retry_delay_minutes,
            retry_on_failure=retry_on_failure,
            request_options=request_options,
        )
        return _response.data

    def get_schedule(
        self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
            Schedule ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScheduleResponse
            Schedule details

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.schedules.get_schedule(
            schedule_id="scheduleId",
        )
        """
        _response = self._raw_client.get_schedule(schedule_id, request_options=request_options)
        return _response.data

    def update_schedule(
        self,
        schedule_id: str,
        *,
        cron_expression: typing.Optional[str] = OMIT,
        day_of_month: typing.Optional[int] = OMIT,
        days_of_week: typing.Optional[typing.Sequence[int]] = OMIT,
        end_date: typing.Optional[dt.date] = OMIT,
        frequency: typing.Optional[ScheduleFrequency] = OMIT,
        max_retries: typing.Optional[int] = OMIT,
        max_runs: typing.Optional[int] = OMIT,
        name: typing.Optional[str] = OMIT,
        retry_delay_minutes: typing.Optional[int] = OMIT,
        retry_on_failure: typing.Optional[bool] = OMIT,
        schedule_time: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
            Schedule ID

        cron_expression : typing.Optional[str]
            Custom cron expression, required when frequency is `custom_cron`

        day_of_month : typing.Optional[int]
            Day of month to run on (1-28)

        days_of_week : typing.Optional[typing.Sequence[int]]
            Days of week to run on (1=Monday through 7=Sunday)

        end_date : typing.Optional[dt.date]
            Date after which the schedule will not execute

        frequency : typing.Optional[ScheduleFrequency]

        max_retries : typing.Optional[int]
            Maximum number of retry attempts per execution (0-10)

        max_runs : typing.Optional[int]
            Maximum number of executions before auto-completing

        name : typing.Optional[str]
            Human-readable name for the schedule

        retry_delay_minutes : typing.Optional[int]
            Minutes to wait before retrying a failed call (1-1440)

        retry_on_failure : typing.Optional[bool]
            Whether to retry the call if it fails

        schedule_time : typing.Optional[str]
            Time of day to execute in HH:MM or HH:MM:SS format

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScheduleResponse
            Schedule updated

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.schedules.update_schedule(
            schedule_id="scheduleId",
        )
        """
        _response = self._raw_client.update_schedule(
            schedule_id,
            cron_expression=cron_expression,
            day_of_month=day_of_month,
            days_of_week=days_of_week,
            end_date=end_date,
            frequency=frequency,
            max_retries=max_retries,
            max_runs=max_runs,
            name=name,
            retry_delay_minutes=retry_delay_minutes,
            retry_on_failure=retry_on_failure,
            schedule_time=schedule_time,
            request_options=request_options,
        )
        return _response.data

    def delete_schedule(self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        schedule_id : str
            Schedule ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.schedules.delete_schedule(
            schedule_id="scheduleId",
        )
        """
        _response = self._raw_client.delete_schedule(schedule_id, request_options=request_options)
        return _response.data

    def pause_schedule(self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        schedule_id : str
            Schedule ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.schedules.pause_schedule(
            schedule_id="scheduleId",
        )
        """
        _response = self._raw_client.pause_schedule(schedule_id, request_options=request_options)
        return _response.data

    def resume_schedule(self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        schedule_id : str
            Schedule ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.schedules.resume_schedule(
            schedule_id="scheduleId",
        )
        """
        _response = self._raw_client.resume_schedule(schedule_id, request_options=request_options)
        return _response.data


class AsyncSchedulesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSchedulesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSchedulesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSchedulesClient
        """
        return self._raw_client

    async def list_schedules(
        self,
        *,
        status: typing.Optional[ScheduleStatus] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ScheduleResponse, ScheduleListResponse]:
        """
        Parameters
        ----------
        status : typing.Optional[ScheduleStatus]
            Filter by status

        limit : typing.Optional[int]
            Max items to return

        offset : typing.Optional[int]
            Items to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ScheduleResponse, ScheduleListResponse]
            Schedule list

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.schedules.list_schedules()
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_schedules(
            status=status, limit=limit, offset=offset, request_options=request_options
        )

    async def create_schedule(
        self,
        *,
        contact_id: str,
        flow_id: str,
        frequency: ScheduleFrequency,
        from_phone_number: str,
        name: str,
        provider_id: str,
        schedule_time: str,
        cron_expression: typing.Optional[str] = OMIT,
        day_of_month: typing.Optional[int] = OMIT,
        days_of_week: typing.Optional[typing.Sequence[int]] = OMIT,
        end_date: typing.Optional[dt.date] = OMIT,
        max_retries: typing.Optional[int] = OMIT,
        max_runs: typing.Optional[int] = OMIT,
        retry_delay_minutes: typing.Optional[int] = OMIT,
        retry_on_failure: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScheduleResponse:
        """
        Parameters
        ----------
        contact_id : str
            Contact to call on each schedule execution

        flow_id : str
            Flow (conversation script) to use for the call

        frequency : ScheduleFrequency
            How often the schedule should repeat

        from_phone_number : str
            Caller ID phone number in E.164 format

        name : str
            Human-readable name for the schedule

        provider_id : str
            VoIP provider to route the call through

        schedule_time : str
            Time of day to execute in HH:MM or HH:MM:SS format

        cron_expression : typing.Optional[str]
            Custom cron expression, required when frequency is `custom_cron`

        day_of_month : typing.Optional[int]
            Day of month to run on (1-28), used with `monthly` frequency

        days_of_week : typing.Optional[typing.Sequence[int]]
            Days of week to run on (1=Monday through 7=Sunday), used with `weekly` frequency

        end_date : typing.Optional[dt.date]
            Date after which the schedule will not execute

        max_retries : typing.Optional[int]
            Maximum number of retry attempts per execution (0-10)

        max_runs : typing.Optional[int]
            Maximum number of executions before auto-completing

        retry_delay_minutes : typing.Optional[int]
            Minutes to wait before retrying a failed call (1-1440)

        retry_on_failure : typing.Optional[bool]
            Whether to retry the call if it fails

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScheduleResponse
            Schedule created

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.schedules.create_schedule(
                contact_id="550e8400-e29b-41d4-a716-446655440000",
                flow_id="550e8400-e29b-41d4-a716-446655440000",
                frequency="once",
                from_phone_number="+15551234567",
                name="Daily Follow-up Call",
                provider_id="550e8400-e29b-41d4-a716-446655440000",
                schedule_time="09:00",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_schedule(
            contact_id=contact_id,
            flow_id=flow_id,
            frequency=frequency,
            from_phone_number=from_phone_number,
            name=name,
            provider_id=provider_id,
            schedule_time=schedule_time,
            cron_expression=cron_expression,
            day_of_month=day_of_month,
            days_of_week=days_of_week,
            end_date=end_date,
            max_retries=max_retries,
            max_runs=max_runs,
            retry_delay_minutes=retry_delay_minutes,
            retry_on_failure=retry_on_failure,
            request_options=request_options,
        )
        return _response.data

    async def get_schedule(
        self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
            Schedule ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScheduleResponse
            Schedule details

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.schedules.get_schedule(
                schedule_id="scheduleId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_schedule(schedule_id, request_options=request_options)
        return _response.data

    async def update_schedule(
        self,
        schedule_id: str,
        *,
        cron_expression: typing.Optional[str] = OMIT,
        day_of_month: typing.Optional[int] = OMIT,
        days_of_week: typing.Optional[typing.Sequence[int]] = OMIT,
        end_date: typing.Optional[dt.date] = OMIT,
        frequency: typing.Optional[ScheduleFrequency] = OMIT,
        max_retries: typing.Optional[int] = OMIT,
        max_runs: typing.Optional[int] = OMIT,
        name: typing.Optional[str] = OMIT,
        retry_delay_minutes: typing.Optional[int] = OMIT,
        retry_on_failure: typing.Optional[bool] = OMIT,
        schedule_time: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ScheduleResponse:
        """
        Parameters
        ----------
        schedule_id : str
            Schedule ID

        cron_expression : typing.Optional[str]
            Custom cron expression, required when frequency is `custom_cron`

        day_of_month : typing.Optional[int]
            Day of month to run on (1-28)

        days_of_week : typing.Optional[typing.Sequence[int]]
            Days of week to run on (1=Monday through 7=Sunday)

        end_date : typing.Optional[dt.date]
            Date after which the schedule will not execute

        frequency : typing.Optional[ScheduleFrequency]

        max_retries : typing.Optional[int]
            Maximum number of retry attempts per execution (0-10)

        max_runs : typing.Optional[int]
            Maximum number of executions before auto-completing

        name : typing.Optional[str]
            Human-readable name for the schedule

        retry_delay_minutes : typing.Optional[int]
            Minutes to wait before retrying a failed call (1-1440)

        retry_on_failure : typing.Optional[bool]
            Whether to retry the call if it fails

        schedule_time : typing.Optional[str]
            Time of day to execute in HH:MM or HH:MM:SS format

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScheduleResponse
            Schedule updated

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.schedules.update_schedule(
                schedule_id="scheduleId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_schedule(
            schedule_id,
            cron_expression=cron_expression,
            day_of_month=day_of_month,
            days_of_week=days_of_week,
            end_date=end_date,
            frequency=frequency,
            max_retries=max_retries,
            max_runs=max_runs,
            name=name,
            retry_delay_minutes=retry_delay_minutes,
            retry_on_failure=retry_on_failure,
            schedule_time=schedule_time,
            request_options=request_options,
        )
        return _response.data

    async def delete_schedule(
        self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        schedule_id : str
            Schedule ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.schedules.delete_schedule(
                schedule_id="scheduleId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_schedule(schedule_id, request_options=request_options)
        return _response.data

    async def pause_schedule(
        self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        schedule_id : str
            Schedule ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.schedules.pause_schedule(
                schedule_id="scheduleId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.pause_schedule(schedule_id, request_options=request_options)
        return _response.data

    async def resume_schedule(
        self, schedule_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        schedule_id : str
            Schedule ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.schedules.resume_schedule(
                schedule_id="scheduleId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resume_schedule(schedule_id, request_options=request_options)
        return _response.data
