# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.bulk_dnc_import_response import BulkDncImportResponse
from ..types.check_dnc_response import CheckDncResponse
from ..types.dnc_entry_response import DncEntryResponse
from ..types.dnc_list_response import DncListResponse
from ..types.dnc_source import DncSource
from .raw_client import AsyncRawDoNotCallClient, RawDoNotCallClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DoNotCallClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDoNotCallClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDoNotCallClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDoNotCallClient
        """
        return self._raw_client

    def list_dnc_entries(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[DncEntryResponse, DncListResponse]:
        """
        List DNC entries for an account with pagination.

        Parameters
        ----------
        limit : typing.Optional[int]
            Max items to return (default: 20)

        offset : typing.Optional[int]
            Items to skip

        search : typing.Optional[str]
            Filter by phone number (partial match)

        source : typing.Optional[str]
            Filter by source (exact match)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[DncEntryResponse, DncListResponse]
            DNC entry list with pagination

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        response = client.do_not_call.list_dnc_entries()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list_dnc_entries(
            limit=limit, offset=offset, search=search, source=source, request_options=request_options
        )

    def add_dnc_entry(
        self,
        *,
        phone_number: str,
        reason: typing.Optional[str] = OMIT,
        source: typing.Optional[DncSource] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Add a phone number to the DNC list.

        Parameters
        ----------
        phone_number : str
            Phone number in E.164 format

        reason : typing.Optional[str]
            Human-readable reason for adding to DNC list (max 500 characters)

        source : typing.Optional[DncSource]
            How this DNC entry was created (default: manual)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.do_not_call.add_dnc_entry(
            phone_number="+15551234567",
        )
        """
        _response = self._raw_client.add_dnc_entry(
            phone_number=phone_number, reason=reason, source=source, request_options=request_options
        )
        return _response.data

    def bulk_import_dnc(
        self,
        *,
        phone_numbers: typing.Sequence[str],
        reason: typing.Optional[str] = OMIT,
        source: typing.Optional[DncSource] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BulkDncImportResponse:
        """
        Bulk import phone numbers to the DNC list.

        Parameters
        ----------
        phone_numbers : typing.Sequence[str]
            Phone numbers in E.164 format (1-10,000 numbers per request)

        reason : typing.Optional[str]
            Human-readable reason applied to all entries (max 500 characters)

        source : typing.Optional[DncSource]
            How these DNC entries were created (default: bulk_import)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkDncImportResponse
            Bulk import result

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.do_not_call.bulk_import_dnc(
            phone_numbers=["+15551234567", "+15559876543"],
        )
        """
        _response = self._raw_client.bulk_import_dnc(
            phone_numbers=phone_numbers, reason=reason, source=source, request_options=request_options
        )
        return _response.data

    def check_dnc_status(
        self, *, phone_numbers: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> CheckDncResponse:
        """
        Check if phone numbers are on the DNC list.

        Parameters
        ----------
        phone_numbers : typing.Sequence[str]
            Phone numbers to check in E.164 format (1-100 numbers per request)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckDncResponse
            DNC check results

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.do_not_call.check_dnc_status(
            phone_numbers=["+15551234567", "+15559876543"],
        )
        """
        _response = self._raw_client.check_dnc_status(phone_numbers=phone_numbers, request_options=request_options)
        return _response.data

    def remove_dnc_entry(self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove a phone number from the DNC list.

        Parameters
        ----------
        phone_number : str
            Phone number to remove (URL-encoded E.164)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.do_not_call.remove_dnc_entry(
            phone_number="phoneNumber",
        )
        """
        _response = self._raw_client.remove_dnc_entry(phone_number, request_options=request_options)
        return _response.data


class AsyncDoNotCallClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDoNotCallClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDoNotCallClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDoNotCallClient
        """
        return self._raw_client

    async def list_dnc_entries(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[DncEntryResponse, DncListResponse]:
        """
        List DNC entries for an account with pagination.

        Parameters
        ----------
        limit : typing.Optional[int]
            Max items to return (default: 20)

        offset : typing.Optional[int]
            Items to skip

        search : typing.Optional[str]
            Filter by phone number (partial match)

        source : typing.Optional[str]
            Filter by source (exact match)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[DncEntryResponse, DncListResponse]
            DNC entry list with pagination

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.do_not_call.list_dnc_entries()
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list_dnc_entries(
            limit=limit, offset=offset, search=search, source=source, request_options=request_options
        )

    async def add_dnc_entry(
        self,
        *,
        phone_number: str,
        reason: typing.Optional[str] = OMIT,
        source: typing.Optional[DncSource] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Add a phone number to the DNC list.

        Parameters
        ----------
        phone_number : str
            Phone number in E.164 format

        reason : typing.Optional[str]
            Human-readable reason for adding to DNC list (max 500 characters)

        source : typing.Optional[DncSource]
            How this DNC entry was created (default: manual)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.do_not_call.add_dnc_entry(
                phone_number="+15551234567",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_dnc_entry(
            phone_number=phone_number, reason=reason, source=source, request_options=request_options
        )
        return _response.data

    async def bulk_import_dnc(
        self,
        *,
        phone_numbers: typing.Sequence[str],
        reason: typing.Optional[str] = OMIT,
        source: typing.Optional[DncSource] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BulkDncImportResponse:
        """
        Bulk import phone numbers to the DNC list.

        Parameters
        ----------
        phone_numbers : typing.Sequence[str]
            Phone numbers in E.164 format (1-10,000 numbers per request)

        reason : typing.Optional[str]
            Human-readable reason applied to all entries (max 500 characters)

        source : typing.Optional[DncSource]
            How these DNC entries were created (default: bulk_import)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkDncImportResponse
            Bulk import result

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.do_not_call.bulk_import_dnc(
                phone_numbers=["+15551234567", "+15559876543"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.bulk_import_dnc(
            phone_numbers=phone_numbers, reason=reason, source=source, request_options=request_options
        )
        return _response.data

    async def check_dnc_status(
        self, *, phone_numbers: typing.Sequence[str], request_options: typing.Optional[RequestOptions] = None
    ) -> CheckDncResponse:
        """
        Check if phone numbers are on the DNC list.

        Parameters
        ----------
        phone_numbers : typing.Sequence[str]
            Phone numbers to check in E.164 format (1-100 numbers per request)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckDncResponse
            DNC check results

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.do_not_call.check_dnc_status(
                phone_numbers=["+15551234567", "+15559876543"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.check_dnc_status(
            phone_numbers=phone_numbers, request_options=request_options
        )
        return _response.data

    async def remove_dnc_entry(
        self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove a phone number from the DNC list.

        Parameters
        ----------
        phone_number : str
            Phone number to remove (URL-encoded E.164)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.do_not_call.remove_dnc_entry(
                phone_number="phoneNumber",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_dnc_entry(phone_number, request_options=request_options)
        return _response.data
