# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .action_definition import ActionDefinition
    from .action_item import ActionItem
    from .added_response import AddedResponse
    from .agent_change_summary import AgentChangeSummary
    from .agent_definition import AgentDefinition
    from .agent_status import AgentStatus
    from .agent_type import AgentType
    from .analytics_cost_breakdown_response import AnalyticsCostBreakdownResponse
    from .analytics_cost_line_item_response import AnalyticsCostLineItemResponse
    from .attempt_bucket import AttemptBucket
    from .available_phone_number import AvailablePhoneNumber
    from .balance_summary_response import BalanceSummaryResponse
    from .balance_transaction_list_response import BalanceTransactionListResponse
    from .balance_transaction_response import BalanceTransactionResponse
    from .billable_type import BillableType
    from .bulk_add_contacts_response import BulkAddContactsResponse
    from .bulk_contact_filter import BulkContactFilter
    from .bulk_dnc_import_response import BulkDncImportResponse
    from .bulk_remove_contacts_response import BulkRemoveContactsResponse
    from .bulk_tag_filter_mode import BulkTagFilterMode
    from .call_cost_breakdown_response import CallCostBreakdownResponse
    from .call_cost_detail import CallCostDetail
    from .call_counts import CallCounts
    from .call_direction import CallDirection
    from .call_end_reason import CallEndReason
    from .call_failure_code import CallFailureCode
    from .call_insights import CallInsights
    from .call_list_meta import CallListMeta
    from .call_list_response import CallListResponse
    from .call_outcome import CallOutcome
    from .call_provider_type import CallProviderType
    from .call_rates import CallRates
    from .call_response import CallResponse
    from .call_source import CallSource
    from .call_status import CallStatus
    from .call_transcript_response import CallTranscriptResponse
    from .call_window_request import CallWindowRequest
    from .call_window_response import CallWindowResponse
    from .campaign_analytics_response import CampaignAnalyticsResponse
    from .campaign_contact_list_response import CampaignContactListResponse
    from .campaign_contact_response import CampaignContactResponse
    from .campaign_contact_status import CampaignContactStatus
    from .campaign_duration_bucket import CampaignDurationBucket
    from .campaign_failure_cause import CampaignFailureCause
    from .campaign_list_response import CampaignListResponse
    from .campaign_metrics import CampaignMetrics
    from .campaign_outcome import CampaignOutcome
    from .campaign_overview import CampaignOverview
    from .campaign_pause_reason import CampaignPauseReason
    from .campaign_performance import CampaignPerformance
    from .campaign_progress import CampaignProgress
    from .campaign_response import CampaignResponse
    from .campaign_status import CampaignStatus
    from .campaign_voicemail import CampaignVoicemail
    from .category_breakdown import CategoryBreakdown
    from .change_summary import ChangeSummary
    from .channel_type import ChannelType
    from .charge_detail_response import ChargeDetailResponse
    from .charge_list_response import ChargeListResponse
    from .charge_response import ChargeResponse
    from .charge_status import ChargeStatus
    from .charge_type_db import ChargeTypeDb
    from .check_dnc_response import CheckDncResponse
    from .connected_flow import ConnectedFlow
    from .connected_phone_summary import ConnectedPhoneSummary
    from .contact import Contact
    from .contact_address import ContactAddress
    from .contact_brief import ContactBrief
    from .contact_list_response import ContactListResponse
    from .contact_pagination_meta import ContactPaginationMeta
    from .contact_search_response import ContactSearchResponse
    from .conversation_metrics import ConversationMetrics
    from .cost_category import CostCategory
    from .cost_line_item_response import CostLineItemResponse
    from .cost_metrics import CostMetrics
    from .create_contact_request import CreateContactRequest
    from .create_public_session_response import CreatePublicSessionResponse
    from .create_web_rtc_call_response import CreateWebRtcCallResponse
    from .detected_intent import DetectedIntent
    from .direction_counts import DirectionCounts
    from .dnc_entry_response import DncEntryResponse
    from .dnc_list_meta import DncListMeta
    from .dnc_list_response import DncListResponse
    from .dnc_source import DncSource
    from .duplicate_strategy import DuplicateStrategy
    from .duration_metrics import DurationMetrics
    from .emotion_option import EmotionOption
    from .error_catalog_response import ErrorCatalogResponse
    from .error_code import ErrorCode
    from .error_code_entry import ErrorCodeEntry
    from .error_reason import ErrorReason
    from .error_response import ErrorResponse
    from .extracted_caller_info import ExtractedCallerInfo
    from .field_error import FieldError
    from .field_error_code_entry import FieldErrorCodeEntry
    from .flow_change import FlowChange
    from .flow_change_type import FlowChangeType
    from .flow_cost_breakdown import FlowCostBreakdown
    from .flow_definition import FlowDefinition
    from .flow_detail_response import FlowDetailResponse
    from .flow_function_list_response import FlowFunctionListResponse
    from .flow_function_response import FlowFunctionResponse
    from .flow_list_response import FlowListResponse
    from .flow_providers_response import FlowProvidersResponse
    from .flow_response import FlowResponse
    from .flow_setting_changes import FlowSettingChanges
    from .flow_stats_response import FlowStatsResponse
    from .flow_status import FlowStatus
    from .flow_template import FlowTemplate
    from .flow_template_list_response import FlowTemplateListResponse
    from .flow_version_detail_response import FlowVersionDetailResponse
    from .flow_version_summary import FlowVersionSummary
    from .function_call_metrics import FunctionCallMetrics
    from .function_definition import FunctionDefinition
    from .generation_config_schema import GenerationConfigSchema
    from .hourly_volume import HourlyVolume
    from .ice_server_entry import IceServerEntry
    from .ice_servers_response import IceServersResponse
    from .import_error import ImportError
    from .import_format import ImportFormat
    from .import_result import ImportResult
    from .invoice_list_response import InvoiceListResponse
    from .invoice_response import InvoiceResponse
    from .invoice_status import InvoiceStatus
    from .language_info import LanguageInfo
    from .latency_metrics import LatencyMetrics
    from .list_meta import ListMeta
    from .llm_capabilities import LlmCapabilities
    from .llm_model import LlmModel
    from .llm_pricing import LlmPricing
    from .llm_provider import LlmProvider
    from .llm_service_definition import LlmServiceDefinition
    from .make_call_response import MakeCallResponse, MakeCallResponse_Initiated, MakeCallResponse_Queued
    from .make_call_response_initiated import MakeCallResponseInitiated
    from .make_call_response_queued import MakeCallResponseQueued
    from .max_call_duration_settings import MaxCallDurationSettings
    from .paginated_response import PaginatedResponse
    from .pagination_meta import PaginationMeta
    from .phone_number_capability import PhoneNumberCapability
    from .phone_number_list_response import PhoneNumberListResponse
    from .phone_number_pricing import PhoneNumberPricing
    from .phone_number_response import PhoneNumberResponse
    from .phone_number_status import PhoneNumberStatus
    from .phone_provider_list_response import PhoneProviderListResponse
    from .phone_provider_response import PhoneProviderResponse
    from .pricing_entry import PricingEntry
    from .prompt_reference import PromptReference
    from .provider_type import ProviderType
    from .public_call_status_response import PublicCallStatusResponse
    from .public_phone_number_pricing import PublicPhoneNumberPricing
    from .public_pricing_response import PublicPricingResponse
    from .publish_flow_response import PublishFlowResponse
    from .queue_info import QueueInfo
    from .range_schema import RangeSchema
    from .rate_info import RateInfo
    from .recording_storage_pricing import RecordingStoragePricing
    from .recording_url_response import RecordingUrlResponse
    from .removed_response import RemovedResponse
    from .request_schema import RequestSchema
    from .rollback_response import RollbackResponse
    from .schedule_frequency import ScheduleFrequency
    from .schedule_list_response import ScheduleListResponse
    from .schedule_response import ScheduleResponse
    from .schedule_status import ScheduleStatus
    from .sentiment_analysis import SentimentAnalysis
    from .service_change_summary import ServiceChangeSummary
    from .service_definition import ServiceDefinition
    from .skipped_contact import SkippedContact
    from .stt_capabilities import SttCapabilities
    from .stt_model import SttModel
    from .stt_pricing import SttPricing
    from .stt_provider import SttProvider
    from .stt_service_definition import SttServiceDefinition
    from .tag_with_count import TagWithCount
    from .tags_list_response import TagsListResponse
    from .telephony_status import TelephonyStatus
    from .time_period import TimePeriod
    from .transaction_status import TransactionStatus
    from .transaction_type import TransactionType
    from .transcript_message import TranscriptMessage
    from .transcript_message_metrics import TranscriptMessageMetrics
    from .transcript_speaker import TranscriptSpeaker
    from .transformation_summary import TransformationSummary
    from .transition_definition import TransitionDefinition
    from .tts_capabilities import TtsCapabilities
    from .tts_model import TtsModel
    from .tts_pricing import TtsPricing
    from .tts_provider import TtsProvider
    from .tts_service_definition import TtsServiceDefinition
    from .usage_metrics import UsageMetrics
    from .user_idle_settings import UserIdleSettings
    from .validation_response import ValidationResponse
    from .voice_dto import VoiceDto
    from .voices_dto import VoicesDto
    from .web_rtc_offer_response import WebRtcOfferResponse
_dynamic_imports: typing.Dict[str, str] = {
    "ActionDefinition": ".action_definition",
    "ActionItem": ".action_item",
    "AddedResponse": ".added_response",
    "AgentChangeSummary": ".agent_change_summary",
    "AgentDefinition": ".agent_definition",
    "AgentStatus": ".agent_status",
    "AgentType": ".agent_type",
    "AnalyticsCostBreakdownResponse": ".analytics_cost_breakdown_response",
    "AnalyticsCostLineItemResponse": ".analytics_cost_line_item_response",
    "AttemptBucket": ".attempt_bucket",
    "AvailablePhoneNumber": ".available_phone_number",
    "BalanceSummaryResponse": ".balance_summary_response",
    "BalanceTransactionListResponse": ".balance_transaction_list_response",
    "BalanceTransactionResponse": ".balance_transaction_response",
    "BillableType": ".billable_type",
    "BulkAddContactsResponse": ".bulk_add_contacts_response",
    "BulkContactFilter": ".bulk_contact_filter",
    "BulkDncImportResponse": ".bulk_dnc_import_response",
    "BulkRemoveContactsResponse": ".bulk_remove_contacts_response",
    "BulkTagFilterMode": ".bulk_tag_filter_mode",
    "CallCostBreakdownResponse": ".call_cost_breakdown_response",
    "CallCostDetail": ".call_cost_detail",
    "CallCounts": ".call_counts",
    "CallDirection": ".call_direction",
    "CallEndReason": ".call_end_reason",
    "CallFailureCode": ".call_failure_code",
    "CallInsights": ".call_insights",
    "CallListMeta": ".call_list_meta",
    "CallListResponse": ".call_list_response",
    "CallOutcome": ".call_outcome",
    "CallProviderType": ".call_provider_type",
    "CallRates": ".call_rates",
    "CallResponse": ".call_response",
    "CallSource": ".call_source",
    "CallStatus": ".call_status",
    "CallTranscriptResponse": ".call_transcript_response",
    "CallWindowRequest": ".call_window_request",
    "CallWindowResponse": ".call_window_response",
    "CampaignAnalyticsResponse": ".campaign_analytics_response",
    "CampaignContactListResponse": ".campaign_contact_list_response",
    "CampaignContactResponse": ".campaign_contact_response",
    "CampaignContactStatus": ".campaign_contact_status",
    "CampaignDurationBucket": ".campaign_duration_bucket",
    "CampaignFailureCause": ".campaign_failure_cause",
    "CampaignListResponse": ".campaign_list_response",
    "CampaignMetrics": ".campaign_metrics",
    "CampaignOutcome": ".campaign_outcome",
    "CampaignOverview": ".campaign_overview",
    "CampaignPauseReason": ".campaign_pause_reason",
    "CampaignPerformance": ".campaign_performance",
    "CampaignProgress": ".campaign_progress",
    "CampaignResponse": ".campaign_response",
    "CampaignStatus": ".campaign_status",
    "CampaignVoicemail": ".campaign_voicemail",
    "CategoryBreakdown": ".category_breakdown",
    "ChangeSummary": ".change_summary",
    "ChannelType": ".channel_type",
    "ChargeDetailResponse": ".charge_detail_response",
    "ChargeListResponse": ".charge_list_response",
    "ChargeResponse": ".charge_response",
    "ChargeStatus": ".charge_status",
    "ChargeTypeDb": ".charge_type_db",
    "CheckDncResponse": ".check_dnc_response",
    "ConnectedFlow": ".connected_flow",
    "ConnectedPhoneSummary": ".connected_phone_summary",
    "Contact": ".contact",
    "ContactAddress": ".contact_address",
    "ContactBrief": ".contact_brief",
    "ContactListResponse": ".contact_list_response",
    "ContactPaginationMeta": ".contact_pagination_meta",
    "ContactSearchResponse": ".contact_search_response",
    "ConversationMetrics": ".conversation_metrics",
    "CostCategory": ".cost_category",
    "CostLineItemResponse": ".cost_line_item_response",
    "CostMetrics": ".cost_metrics",
    "CreateContactRequest": ".create_contact_request",
    "CreatePublicSessionResponse": ".create_public_session_response",
    "CreateWebRtcCallResponse": ".create_web_rtc_call_response",
    "DetectedIntent": ".detected_intent",
    "DirectionCounts": ".direction_counts",
    "DncEntryResponse": ".dnc_entry_response",
    "DncListMeta": ".dnc_list_meta",
    "DncListResponse": ".dnc_list_response",
    "DncSource": ".dnc_source",
    "DuplicateStrategy": ".duplicate_strategy",
    "DurationMetrics": ".duration_metrics",
    "EmotionOption": ".emotion_option",
    "ErrorCatalogResponse": ".error_catalog_response",
    "ErrorCode": ".error_code",
    "ErrorCodeEntry": ".error_code_entry",
    "ErrorReason": ".error_reason",
    "ErrorResponse": ".error_response",
    "ExtractedCallerInfo": ".extracted_caller_info",
    "FieldError": ".field_error",
    "FieldErrorCodeEntry": ".field_error_code_entry",
    "FlowChange": ".flow_change",
    "FlowChangeType": ".flow_change_type",
    "FlowCostBreakdown": ".flow_cost_breakdown",
    "FlowDefinition": ".flow_definition",
    "FlowDetailResponse": ".flow_detail_response",
    "FlowFunctionListResponse": ".flow_function_list_response",
    "FlowFunctionResponse": ".flow_function_response",
    "FlowListResponse": ".flow_list_response",
    "FlowProvidersResponse": ".flow_providers_response",
    "FlowResponse": ".flow_response",
    "FlowSettingChanges": ".flow_setting_changes",
    "FlowStatsResponse": ".flow_stats_response",
    "FlowStatus": ".flow_status",
    "FlowTemplate": ".flow_template",
    "FlowTemplateListResponse": ".flow_template_list_response",
    "FlowVersionDetailResponse": ".flow_version_detail_response",
    "FlowVersionSummary": ".flow_version_summary",
    "FunctionCallMetrics": ".function_call_metrics",
    "FunctionDefinition": ".function_definition",
    "GenerationConfigSchema": ".generation_config_schema",
    "HourlyVolume": ".hourly_volume",
    "IceServerEntry": ".ice_server_entry",
    "IceServersResponse": ".ice_servers_response",
    "ImportError": ".import_error",
    "ImportFormat": ".import_format",
    "ImportResult": ".import_result",
    "InvoiceListResponse": ".invoice_list_response",
    "InvoiceResponse": ".invoice_response",
    "InvoiceStatus": ".invoice_status",
    "LanguageInfo": ".language_info",
    "LatencyMetrics": ".latency_metrics",
    "ListMeta": ".list_meta",
    "LlmCapabilities": ".llm_capabilities",
    "LlmModel": ".llm_model",
    "LlmPricing": ".llm_pricing",
    "LlmProvider": ".llm_provider",
    "LlmServiceDefinition": ".llm_service_definition",
    "MakeCallResponse": ".make_call_response",
    "MakeCallResponseInitiated": ".make_call_response_initiated",
    "MakeCallResponseQueued": ".make_call_response_queued",
    "MakeCallResponse_Initiated": ".make_call_response",
    "MakeCallResponse_Queued": ".make_call_response",
    "MaxCallDurationSettings": ".max_call_duration_settings",
    "PaginatedResponse": ".paginated_response",
    "PaginationMeta": ".pagination_meta",
    "PhoneNumberCapability": ".phone_number_capability",
    "PhoneNumberListResponse": ".phone_number_list_response",
    "PhoneNumberPricing": ".phone_number_pricing",
    "PhoneNumberResponse": ".phone_number_response",
    "PhoneNumberStatus": ".phone_number_status",
    "PhoneProviderListResponse": ".phone_provider_list_response",
    "PhoneProviderResponse": ".phone_provider_response",
    "PricingEntry": ".pricing_entry",
    "PromptReference": ".prompt_reference",
    "ProviderType": ".provider_type",
    "PublicCallStatusResponse": ".public_call_status_response",
    "PublicPhoneNumberPricing": ".public_phone_number_pricing",
    "PublicPricingResponse": ".public_pricing_response",
    "PublishFlowResponse": ".publish_flow_response",
    "QueueInfo": ".queue_info",
    "RangeSchema": ".range_schema",
    "RateInfo": ".rate_info",
    "RecordingStoragePricing": ".recording_storage_pricing",
    "RecordingUrlResponse": ".recording_url_response",
    "RemovedResponse": ".removed_response",
    "RequestSchema": ".request_schema",
    "RollbackResponse": ".rollback_response",
    "ScheduleFrequency": ".schedule_frequency",
    "ScheduleListResponse": ".schedule_list_response",
    "ScheduleResponse": ".schedule_response",
    "ScheduleStatus": ".schedule_status",
    "SentimentAnalysis": ".sentiment_analysis",
    "ServiceChangeSummary": ".service_change_summary",
    "ServiceDefinition": ".service_definition",
    "SkippedContact": ".skipped_contact",
    "SttCapabilities": ".stt_capabilities",
    "SttModel": ".stt_model",
    "SttPricing": ".stt_pricing",
    "SttProvider": ".stt_provider",
    "SttServiceDefinition": ".stt_service_definition",
    "TagWithCount": ".tag_with_count",
    "TagsListResponse": ".tags_list_response",
    "TelephonyStatus": ".telephony_status",
    "TimePeriod": ".time_period",
    "TransactionStatus": ".transaction_status",
    "TransactionType": ".transaction_type",
    "TranscriptMessage": ".transcript_message",
    "TranscriptMessageMetrics": ".transcript_message_metrics",
    "TranscriptSpeaker": ".transcript_speaker",
    "TransformationSummary": ".transformation_summary",
    "TransitionDefinition": ".transition_definition",
    "TtsCapabilities": ".tts_capabilities",
    "TtsModel": ".tts_model",
    "TtsPricing": ".tts_pricing",
    "TtsProvider": ".tts_provider",
    "TtsServiceDefinition": ".tts_service_definition",
    "UsageMetrics": ".usage_metrics",
    "UserIdleSettings": ".user_idle_settings",
    "ValidationResponse": ".validation_response",
    "VoiceDto": ".voice_dto",
    "VoicesDto": ".voices_dto",
    "WebRtcOfferResponse": ".web_rtc_offer_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ActionDefinition",
    "ActionItem",
    "AddedResponse",
    "AgentChangeSummary",
    "AgentDefinition",
    "AgentStatus",
    "AgentType",
    "AnalyticsCostBreakdownResponse",
    "AnalyticsCostLineItemResponse",
    "AttemptBucket",
    "AvailablePhoneNumber",
    "BalanceSummaryResponse",
    "BalanceTransactionListResponse",
    "BalanceTransactionResponse",
    "BillableType",
    "BulkAddContactsResponse",
    "BulkContactFilter",
    "BulkDncImportResponse",
    "BulkRemoveContactsResponse",
    "BulkTagFilterMode",
    "CallCostBreakdownResponse",
    "CallCostDetail",
    "CallCounts",
    "CallDirection",
    "CallEndReason",
    "CallFailureCode",
    "CallInsights",
    "CallListMeta",
    "CallListResponse",
    "CallOutcome",
    "CallProviderType",
    "CallRates",
    "CallResponse",
    "CallSource",
    "CallStatus",
    "CallTranscriptResponse",
    "CallWindowRequest",
    "CallWindowResponse",
    "CampaignAnalyticsResponse",
    "CampaignContactListResponse",
    "CampaignContactResponse",
    "CampaignContactStatus",
    "CampaignDurationBucket",
    "CampaignFailureCause",
    "CampaignListResponse",
    "CampaignMetrics",
    "CampaignOutcome",
    "CampaignOverview",
    "CampaignPauseReason",
    "CampaignPerformance",
    "CampaignProgress",
    "CampaignResponse",
    "CampaignStatus",
    "CampaignVoicemail",
    "CategoryBreakdown",
    "ChangeSummary",
    "ChannelType",
    "ChargeDetailResponse",
    "ChargeListResponse",
    "ChargeResponse",
    "ChargeStatus",
    "ChargeTypeDb",
    "CheckDncResponse",
    "ConnectedFlow",
    "ConnectedPhoneSummary",
    "Contact",
    "ContactAddress",
    "ContactBrief",
    "ContactListResponse",
    "ContactPaginationMeta",
    "ContactSearchResponse",
    "ConversationMetrics",
    "CostCategory",
    "CostLineItemResponse",
    "CostMetrics",
    "CreateContactRequest",
    "CreatePublicSessionResponse",
    "CreateWebRtcCallResponse",
    "DetectedIntent",
    "DirectionCounts",
    "DncEntryResponse",
    "DncListMeta",
    "DncListResponse",
    "DncSource",
    "DuplicateStrategy",
    "DurationMetrics",
    "EmotionOption",
    "ErrorCatalogResponse",
    "ErrorCode",
    "ErrorCodeEntry",
    "ErrorReason",
    "ErrorResponse",
    "ExtractedCallerInfo",
    "FieldError",
    "FieldErrorCodeEntry",
    "FlowChange",
    "FlowChangeType",
    "FlowCostBreakdown",
    "FlowDefinition",
    "FlowDetailResponse",
    "FlowFunctionListResponse",
    "FlowFunctionResponse",
    "FlowListResponse",
    "FlowProvidersResponse",
    "FlowResponse",
    "FlowSettingChanges",
    "FlowStatsResponse",
    "FlowStatus",
    "FlowTemplate",
    "FlowTemplateListResponse",
    "FlowVersionDetailResponse",
    "FlowVersionSummary",
    "FunctionCallMetrics",
    "FunctionDefinition",
    "GenerationConfigSchema",
    "HourlyVolume",
    "IceServerEntry",
    "IceServersResponse",
    "ImportError",
    "ImportFormat",
    "ImportResult",
    "InvoiceListResponse",
    "InvoiceResponse",
    "InvoiceStatus",
    "LanguageInfo",
    "LatencyMetrics",
    "ListMeta",
    "LlmCapabilities",
    "LlmModel",
    "LlmPricing",
    "LlmProvider",
    "LlmServiceDefinition",
    "MakeCallResponse",
    "MakeCallResponseInitiated",
    "MakeCallResponseQueued",
    "MakeCallResponse_Initiated",
    "MakeCallResponse_Queued",
    "MaxCallDurationSettings",
    "PaginatedResponse",
    "PaginationMeta",
    "PhoneNumberCapability",
    "PhoneNumberListResponse",
    "PhoneNumberPricing",
    "PhoneNumberResponse",
    "PhoneNumberStatus",
    "PhoneProviderListResponse",
    "PhoneProviderResponse",
    "PricingEntry",
    "PromptReference",
    "ProviderType",
    "PublicCallStatusResponse",
    "PublicPhoneNumberPricing",
    "PublicPricingResponse",
    "PublishFlowResponse",
    "QueueInfo",
    "RangeSchema",
    "RateInfo",
    "RecordingStoragePricing",
    "RecordingUrlResponse",
    "RemovedResponse",
    "RequestSchema",
    "RollbackResponse",
    "ScheduleFrequency",
    "ScheduleListResponse",
    "ScheduleResponse",
    "ScheduleStatus",
    "SentimentAnalysis",
    "ServiceChangeSummary",
    "ServiceDefinition",
    "SkippedContact",
    "SttCapabilities",
    "SttModel",
    "SttPricing",
    "SttProvider",
    "SttServiceDefinition",
    "TagWithCount",
    "TagsListResponse",
    "TelephonyStatus",
    "TimePeriod",
    "TransactionStatus",
    "TransactionType",
    "TranscriptMessage",
    "TranscriptMessageMetrics",
    "TranscriptSpeaker",
    "TransformationSummary",
    "TransitionDefinition",
    "TtsCapabilities",
    "TtsModel",
    "TtsPricing",
    "TtsProvider",
    "TtsServiceDefinition",
    "UsageMetrics",
    "UserIdleSettings",
    "ValidationResponse",
    "VoiceDto",
    "VoicesDto",
    "WebRtcOfferResponse",
]
