# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AnalyticsCostLineItemResponse(UniversalBaseModel):
    """
    Single cost line item for API response
    """

    amount_microcents: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="amountMicrocents"),
        pydantic.Field(alias="amountMicrocents", description="Amount in microcents"),
    ]
    """
    Amount in microcents
    """

    amount_usd: typing_extensions.Annotated[
        float, FieldMetadata(alias="amountUsd"), pydantic.Field(alias="amountUsd", description="Amount in USD")
    ]
    """
    Amount in USD
    """

    category: str = pydantic.Field()
    """
    Cost category identifier
    """

    category_display: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="categoryDisplay"),
        pydantic.Field(alias="categoryDisplay", description="Human-readable category name"),
    ]
    """
    Human-readable category name
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When this line item was created"),
    ]
    """
    When this line item was created
    """

    id: str = pydantic.Field()
    """
    Line item identifier
    """

    rate_microcents: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="rateMicrocents"),
        pydantic.Field(alias="rateMicrocents", description="Rate in microcents per unit"),
    ] = None
    """
    Rate in microcents per unit
    """

    rate_unit: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="rateUnit"),
        pydantic.Field(alias="rateUnit", description="Rate unit description"),
    ] = None
    """
    Rate unit description
    """

    usage_data: typing_extensions.Annotated[
        typing.Dict[str, typing.Any],
        FieldMetadata(alias="usageData"),
        pydantic.Field(alias="usageData", description="Additional usage metadata"),
    ]
    """
    Additional usage metadata
    """

    usage_quantity: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="usageQuantity"),
        pydantic.Field(alias="usageQuantity", description="Usage quantity (e.g., token count, character count)"),
    ] = None
    """
    Usage quantity (e.g., token count, character count)
    """

    usage_unit: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="usageUnit"),
        pydantic.Field(alias="usageUnit", description='Unit of usage (e.g., "tokens", "characters", "minutes")'),
    ] = None
    """
    Unit of usage (e.g., "tokens", "characters", "minutes")
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
