# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AppDestinationConfig(UniversalBaseModel):
    """
    Configuration of a "Your app" destination: the HTTPS endpoint of your
    server that receives transfer offers.
    """

    url: str = pydantic.Field()
    """
    HTTPS URL that receives signed `transfer.offer` webhooks
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
