# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AvailableNumbersEcho(UniversalBaseModel):
    """
    Search criteria echoed back with the results
    """

    area_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="areaCode"),
        pydantic.Field(alias="areaCode", description="Area code filter that was applied, if any"),
    ] = None
    """
    Area code filter that was applied, if any
    """

    contains: typing.Optional[str] = pydantic.Field(default=None)
    """
    Pattern filter that was applied, if any
    """

    country_code: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="countryCode"),
        pydantic.Field(alias="countryCode", description="ISO country code that was searched"),
    ]
    """
    ISO country code that was searched
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
