# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .balance_transaction_response import BalanceTransactionResponse
from .pagination_meta import PaginationMeta


class BalanceTransactionListResponse(UniversalBaseModel):
    """
    Page of balance transactions
    """

    meta: PaginationMeta = pydantic.Field()
    """
    Pagination metadata
    """

    transactions: typing.List[BalanceTransactionResponse] = pydantic.Field()
    """
    Items on this page
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
