# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class BalanceSummaryResponse(UniversalBaseModel):
    """
    Balance summary for an account
    """

    available: str = pydantic.Field()
    """
    Total available balance across all non-expired buckets (USD)
    """

    bonus_balance: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="bonusBalance"),
        pydantic.Field(alias="bonusBalance", description="Balance from bonuses and promotions"),
    ]
    """
    Balance from bonuses and promotions
    """

    earliest_expiration: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="earliestExpiration"),
        pydantic.Field(
            alias="earliestExpiration", description="Earliest expiration date among all balance buckets, if any"
        ),
    ] = None
    """
    Earliest expiration date among all balance buckets, if any
    """

    purchased_balance: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="purchasedBalance"),
        pydantic.Field(alias="purchasedBalance", description="Balance from direct purchases (never expires)"),
    ]
    """
    Balance from direct purchases (never expires)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
