# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bulk_tag_filter_mode import BulkTagFilterMode


class BulkContactFilter(UniversalBaseModel):
    """
    Filter criteria for bulk adding contacts to a campaign

    At least one filter must be provided. Filters are combined with AND logic:
    - If both `tags` and `company` are specified, contacts must match BOTH
    - Use `tagMode` to control tag matching: "any" (OR) or "all" (AND)
    """

    company: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter by company name (exact match, case-sensitive)
    """

    search: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full-text search across name, company, occupation, and email
    """

    tag_mode: typing_extensions.Annotated[
        typing.Optional[BulkTagFilterMode],
        FieldMetadata(alias="tagMode"),
        pydantic.Field(alias="tagMode", description="How to match multiple tags: `any` (OR, default) or `all` (AND)"),
    ] = None
    """
    How to match multiple tags: `any` (OR, default) or `all` (AND)
    """

    tags: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Tags to filter by, matching behavior controlled by `tagMode`
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
