# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkAddContactsResponse(UniversalBaseModel):
    """
    Response for bulk add operation
    """

    added: int = pydantic.Field()
    """
    Number of contacts successfully added to the campaign
    """

    matched: int = pydantic.Field()
    """
    Total number of contacts that matched the filter criteria
    """

    skipped: int = pydantic.Field()
    """
    Number of contacts skipped because they were already in the campaign
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
