# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CallListMeta(UniversalBaseModel):
    """
    Pagination metadata for list responses
    """

    limit: int = pydantic.Field()
    """
    Maximum number of items per page
    """

    offset: int = pydantic.Field()
    """
    Number of items skipped (offset into the result set)
    """

    total: int = pydantic.Field()
    """
    Total number of matching records across all pages
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
