# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .analytics_cost_line_item_response import AnalyticsCostLineItemResponse


class CallCostBreakdownResponse(UniversalBaseModel):
    """
    Individual call cost breakdown response
    """

    call_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="callId"), pydantic.Field(alias="callId", description="Call identifier")
    ]
    """
    Call identifier
    """

    line_items: typing_extensions.Annotated[
        typing.List[AnalyticsCostLineItemResponse],
        FieldMetadata(alias="lineItems"),
        pydantic.Field(alias="lineItems", description="Individual cost line items"),
    ]
    """
    Individual cost line items
    """

    total_microcents: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="totalMicrocents"),
        pydantic.Field(alias="totalMicrocents", description="Total cost in microcents"),
    ]
    """
    Total cost in microcents
    """

    total_usd: typing_extensions.Annotated[
        float, FieldMetadata(alias="totalUsd"), pydantic.Field(alias="totalUsd", description="Total cost in USD")
    ]
    """
    Total cost in USD
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
