# This file was auto-generated by Fern from our API Definition.

import typing

CallEndReason = typing.Union[
    typing.Literal[
        "caller_hangup",
        "agent_completed",
        "agent_error",
        "agent_unavailable",
        "agent_timeout",
        "agent_crashed",
        "no_answer",
        "busy",
        "canceled",
        "telephony_error",
        "balance_depleted",
        "reconciled",
    ],
    typing.Any,
]
