# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CallCounts(UniversalBaseModel):
    """
    Call count breakdown
    """

    completed: int = pydantic.Field()
    """
    Calls that completed successfully
    """

    failed: int = pydantic.Field()
    """
    Calls that failed due to errors
    """

    in_progress: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="inProgress"),
        pydantic.Field(alias="inProgress", description="Calls currently in progress"),
    ]
    """
    Calls currently in progress
    """

    no_answer: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="noAnswer"),
        pydantic.Field(alias="noAnswer", description="Calls where the recipient did not answer"),
    ]
    """
    Calls where the recipient did not answer
    """

    total: int = pydantic.Field()
    """
    Total number of calls in the period
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
