# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CampaignOverview(UniversalBaseModel):
    """
    Campaign overview totals
    """

    avg_duration_seconds: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="avgDurationSeconds"),
        pydantic.Field(alias="avgDurationSeconds", description="Average call duration in seconds"),
    ]
    """
    Average call duration in seconds
    """

    completed: int = pydantic.Field()
    """
    Calls that completed successfully
    """

    failed: int = pydantic.Field()
    """
    Calls that failed
    """

    no_answer: typing_extensions.Annotated[
        int, FieldMetadata(alias="noAnswer"), pydantic.Field(alias="noAnswer", description="Calls with no answer")
    ]
    """
    Calls with no answer
    """

    skipped: int = pydantic.Field()
    """
    Contacts skipped (DNC, opt-out)
    """

    success_rate: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="successRate"),
        pydantic.Field(alias="successRate", description="Success rate percentage (0-100)"),
    ]
    """
    Success rate percentage (0-100)
    """

    total_calls: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="totalCalls"),
        pydantic.Field(alias="totalCalls", description="Total calls made in the campaign"),
    ]
    """
    Total calls made in the campaign
    """

    total_cost: typing_extensions.Annotated[
        str, FieldMetadata(alias="totalCost"), pydantic.Field(alias="totalCost", description="Total cost in USD")
    ]
    """
    Total cost in USD
    """

    total_duration_seconds: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="totalDurationSeconds"),
        pydantic.Field(alias="totalDurationSeconds", description="Total call duration in seconds"),
    ]
    """
    Total call duration in seconds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
