# This file was auto-generated by Fern from our API Definition.

import typing

CampaignContactStatus = typing.Union[
    typing.Literal["pending", "queued", "calling", "completed", "failed", "no_answer", "skipped"], typing.Any
]
