# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .campaign_contact_status import CampaignContactStatus


class CampaignContactResponse(UniversalBaseModel):
    """
    Campaign contact response
    """

    attempt_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="attemptCount"),
        pydantic.Field(alias="attemptCount", description="Number of call attempts made so far"),
    ]
    """
    Number of call attempts made so far
    """

    call_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="callId"),
        pydantic.Field(alias="callId", description="ID of the latest call for this contact"),
    ] = None
    """
    ID of the latest call for this contact
    """

    completed_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="completedAt"),
        pydantic.Field(alias="completedAt", description="When the latest call completed"),
    ] = None
    """
    When the latest call completed
    """

    contact_email: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="contactEmail"),
        pydantic.Field(alias="contactEmail", description="Snapshotted contact email from when the contact was added"),
    ] = None
    """
    Snapshotted contact email from when the contact was added
    """

    contact_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="contactId"),
        pydantic.Field(alias="contactId", description="Underlying contact ID from the contacts table"),
    ]
    """
    Underlying contact ID from the contacts table
    """

    contact_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="contactName"),
        pydantic.Field(alias="contactName", description="Snapshotted contact name from when the contact was added"),
    ] = None
    """
    Snapshotted contact name from when the contact was added
    """

    failure_reason: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="failureReason"),
        pydantic.Field(
            alias="failureReason", description="Failure reason from the latest call, or skip reason if skipped"
        ),
    ] = None
    """
    Failure reason from the latest call, or skip reason if skipped
    """

    id: str = pydantic.Field()
    """
    Unique identifier for this campaign contact entry
    """

    max_attempts: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="maxAttempts"),
        pydantic.Field(alias="maxAttempts", description="Maximum allowed call attempts"),
    ]
    """
    Maximum allowed call attempts
    """

    phone_number: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="phoneNumber"),
        pydantic.Field(alias="phoneNumber", description="Contact's phone number in E.164 format"),
    ]
    """
    Contact's phone number in E.164 format
    """

    priority: int = pydantic.Field()
    """
    Queue priority (lower value = higher priority)
    """

    skipped_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="skippedAt"),
        pydantic.Field(alias="skippedAt", description="When the contact was skipped (if status is `skipped`)"),
    ] = None
    """
    When the contact was skipped (if status is `skipped`)
    """

    status: CampaignContactStatus = pydantic.Field()
    """
    Derived status based on the latest call record
    """

    timezone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Contact's IANA timezone (used when `respectContactTimezone` is enabled)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
