# This file was auto-generated by Fern from our API Definition.

import typing

CampaignPauseReason = typing.Union[
    typing.Literal["manual", "insufficient_balance", "system_limit", "provider_error", "canceling"], typing.Any
]
