# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .campaign_response import CampaignResponse
from .list_meta import ListMeta


class CampaignListResponse(UniversalBaseModel):
    """
    Paginated list of campaigns
    """

    campaigns: typing.List[CampaignResponse] = pydantic.Field()
    """
    List of campaigns for the current page
    """

    meta: ListMeta = pydantic.Field()
    """
    Pagination metadata
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
