# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CampaignVoicemail(UniversalBaseModel):
    """
    Answering-machine detection outcomes.
    """

    human: int
    undetermined: int
    voicemail: int
    voicemail_rate: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="voicemailRate"),
        pydantic.Field(
            alias="voicemailRate",
            description="Voicemail as a share of calls where detection reached a verdict (0-100).\nNull when nothing was ever classified.",
        ),
    ] = None
    """
    Voicemail as a share of calls where detection reached a verdict (0-100).
    Null when nothing was ever classified.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
