# This file was auto-generated by Fern from our API Definition.

import typing

ChargeTypeDb = typing.Union[
    typing.Literal[
        "call_usage",
        "phone_purchase",
        "phone_rental",
        "call_analysis",
        "voicemail_classification",
        "adjustment",
        "reservation",
        "recording_storage",
        "assistant_usage",
    ],
    typing.Any,
]
