# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CheckDncResponse(UniversalBaseModel):
    """
    DNC check response for one or more phone numbers
    """

    results: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Map of phone number to blocked status (true = on DNC list)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
