# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ConnectedPhoneSummary(UniversalBaseModel):
    """
    Minimal phone number info for flow listing
    """

    friendly_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="friendlyName"),
        pydantic.Field(alias="friendlyName", description="Human-readable label for the phone number"),
    ] = None
    """
    Human-readable label for the phone number
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the phone number resource
    """

    phone_number: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="phoneNumber"),
        pydantic.Field(alias="phoneNumber", description="Phone number in E.164 format"),
    ]
    """
    Phone number in E.164 format
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
