# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .contact import Contact
from .contact_pagination_meta import ContactPaginationMeta


class ContactListResponse(UniversalBaseModel):
    """
    Contact list response
    """

    contacts: typing.List[Contact] = pydantic.Field()
    """
    List of contacts matching the query
    """

    meta: ContactPaginationMeta = pydantic.Field()
    """
    Pagination metadata
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
