# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ContactAddress(UniversalBaseModel):
    """
    Contact address structure
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    City name
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    Country name or ISO code
    """

    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    State or province
    """

    street: typing.Optional[str] = pydantic.Field(default=None)
    """
    Street address line
    """

    zip: typing.Optional[str] = pydantic.Field(default=None)
    """
    Postal or ZIP code
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
