# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .billable_type import BillableType
from .cost_category import CostCategory


class CostLineItemResponse(UniversalBaseModel):
    """
    Cost line item response for API
    """

    amount_usd: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="amountUsd"),
        pydantic.Field(alias="amountUsd", description="Amount in USD (converted from microcents)"),
    ]
    """
    Amount in USD (converted from microcents)
    """

    billable_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="billableId"),
        pydantic.Field(alias="billableId", description="ID of the billable entity (call ID, phone ID, etc.)"),
    ]
    """
    ID of the billable entity (call ID, phone ID, etc.)
    """

    billable_type: typing_extensions.Annotated[
        BillableType,
        FieldMetadata(alias="billableType"),
        pydantic.Field(alias="billableType", description="Type of billable entity this line item belongs to"),
    ]
    """
    Type of billable entity this line item belongs to
    """

    category: CostCategory = pydantic.Field()
    """
    Cost category for this line item
    """

    category_display: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="categoryDisplay"),
        pydantic.Field(alias="categoryDisplay", description="Human-readable category label"),
    ]
    """
    Human-readable category label
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When this line item was created"),
    ]
    """
    When this line item was created
    """

    id: str = pydantic.Field()
    """
    Unique line item identifier
    """

    rate_microcents: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="rateMicrocents"),
        pydantic.Field(alias="rateMicrocents", description="Rate applied in microcents"),
    ] = None
    """
    Rate applied in microcents
    """

    rate_unit: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="rateUnit"),
        pydantic.Field(alias="rateUnit", description='Rate unit (e.g., "per_1k_tokens", "per_minute")'),
    ] = None
    """
    Rate unit (e.g., "per_1k_tokens", "per_minute")
    """

    usage_data: typing_extensions.Annotated[
        typing.Dict[str, typing.Any],
        FieldMetadata(alias="usageData"),
        pydantic.Field(alias="usageData", description="Category-specific usage details (provider, model, etc.)"),
    ]
    """
    Category-specific usage details (provider, model, etc.)
    """

    usage_quantity: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="usageQuantity"),
        pydantic.Field(alias="usageQuantity", description="Primary usage quantity (tokens, characters, seconds, etc.)"),
    ] = None
    """
    Primary usage quantity (tokens, characters, seconds, etc.)
    """

    usage_unit: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="usageUnit"),
        pydantic.Field(alias="usageUnit", description="Unit of the usage quantity"),
    ] = None
    """
    Unit of the usage quantity
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
