# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DetectedIntent(UniversalBaseModel):
    """
    Intent detected from the conversation by AI analysis
    """

    confidence: typing.Optional[str] = pydantic.Field(default=None)
    """
    Confidence level: "high", "medium", or "low"
    """

    name: str = pydantic.Field()
    """
    Intent name describing what the caller wanted
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
