# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DncEntryResponse(UniversalBaseModel):
    """
    DNC entry response
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the DNC entry was created in the system"),
    ]
    """
    When the DNC entry was created in the system
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the DNC entry
    """

    phone_number: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="phoneNumber"),
        pydantic.Field(alias="phoneNumber", description="Phone number on the DNC list in E.164 format"),
    ]
    """
    Phone number on the DNC list in E.164 format
    """

    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable reason for the DNC entry
    """

    requested_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="requestedAt"),
        pydantic.Field(alias="requestedAt", description="When the DNC request was made"),
    ]
    """
    When the DNC request was made
    """

    source: str = pydantic.Field()
    """
    How this entry was added (manual, api, call_opt_out, bulk_import)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
