# This file was auto-generated by Fern from our API Definition.

import typing

ErrorReason = typing.Union[
    typing.Literal[
        "INVALID_PHONE_FORMAT",
        "MISSING_REQUIRED_FIELD",
        "EMAIL_INVALID_FORMAT",
        "PHONE_ALREADY_EXISTS",
        "PARSE_ERROR",
        "VALIDATION_FAILED",
    ],
    typing.Any,
]
