# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ExtractedCallerInfo(UniversalBaseModel):
    """
    Caller information extracted from the call transcript by AI analysis
    """

    company: typing.Optional[str] = pydantic.Field(default=None)
    """
    Caller's company or organization
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Caller's email address if provided
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Caller's name as mentioned during the conversation
    """

    role: typing.Optional[str] = pydantic.Field(default=None)
    """
    Caller's job title or role
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
