# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FlowTemplate(UniversalBaseModel):
    """
    Flow template - can be system-wide (account_id = None) or account-specific
    """

    account_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="accountId"),
        pydantic.Field(alias="accountId", description="Account that owns this template (null for system templates)"),
    ] = None
    """
    Account that owns this template (null for system templates)
    """

    category: str = pydantic.Field()
    """
    Template category for filtering
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the template was created"),
    ]
    """
    When the template was created
    """

    created_by: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdBy"),
        pydantic.Field(alias="createdBy", description="User who created this template"),
    ] = None
    """
    User who created this template
    """

    definition: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Runtime FlowDefinition (initialNode + services + nodes). This is what
    instantiation copies into the new flow's definition. Null on legacy
    templates that only carry builder nodes/edges.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Brief description of what the template does
    """

    display_order: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="displayOrder"),
        pydantic.Field(alias="displayOrder", description="Sort order for template listing (lower = first)"),
    ]
    """
    Sort order for template listing (lower = first)
    """

    edges: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Flow edge connections between nodes
    """

    icon: typing.Optional[str] = pydantic.Field(default=None)
    """
    Icon identifier or emoji for display
    """

    id: str = pydantic.Field()
    """
    Unique template identifier
    """

    initial_node: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="initialNode"),
        pydantic.Field(alias="initialNode", description="ID of the first node to execute"),
    ]
    """
    ID of the first node to execute
    """

    is_active: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isActive"),
        pydantic.Field(alias="isActive", description="Whether this template is available for use"),
    ]
    """
    Whether this template is available for use
    """

    name: str = pydantic.Field()
    """
    Template display name
    """

    nodes: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Flow node definitions
    """

    preview_image_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="previewImageUrl"),
        pydantic.Field(alias="previewImageUrl", description="URL to a preview image for the template"),
    ] = None
    """
    URL to a preview image for the template
    """

    slug: str = pydantic.Field()
    """
    URL-safe slug for the template
    """

    tags: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Searchable tags
    """

    updated_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="When the template was last modified"),
    ]
    """
    When the template was last modified
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
