# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FlowCostBreakdown(UniversalBaseModel):
    """
    Flow-level cost aggregation
    """

    flow_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="flowId"), pydantic.Field(alias="flowId", description="Unique identifier of the flow")
    ]
    """
    Unique identifier of the flow
    """

    flow_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="flowName"),
        pydantic.Field(alias="flowName", description="Flow display name"),
    ] = None
    """
    Flow display name
    """

    total_microcents: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="totalMicrocents"),
        pydantic.Field(alias="totalMicrocents", description="Total cost in microcents"),
    ]
    """
    Total cost in microcents
    """

    total_usd: typing_extensions.Annotated[
        float, FieldMetadata(alias="totalUsd"), pydantic.Field(alias="totalUsd", description="Total cost in USD")
    ]
    """
    Total cost in USD
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
