# This file was auto-generated by Fern from our API Definition.

import typing

FlowChangeType = typing.Union[
    typing.Literal["agent_added", "agent_removed", "agent_modified", "service_changed", "flow_setting_changed"],
    typing.Any,
]
