# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FlowVersionSummary(UniversalBaseModel):
    """
    Lightweight version summary for flow list responses

    Provides just enough data for version picker dropdowns
    without the full definition.
    """

    notes: typing.Optional[str] = pydantic.Field(default=None)
    """
    Changelog notes for this version
    """

    published_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="publishedAt"),
        pydantic.Field(alias="publishedAt", description="Timestamp when this version was published"),
    ]
    """
    Timestamp when this version was published
    """

    version: str = pydantic.Field()
    """
    Semantic version string (X.Y.Z)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
