# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .change_summary import ChangeSummary
from .flow_definition import FlowDefinition


class FlowVersionDetailResponse(UniversalBaseModel):
    """
    Flow version detail response (includes full flow data)
    """

    bot_version: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="botVersion"),
        pydantic.Field(alias="botVersion", description="Bot runtime version used for this published version"),
    ] = None
    """
    Bot runtime version used for this published version
    """

    change_summary: typing_extensions.Annotated[
        typing.Optional[ChangeSummary], FieldMetadata(alias="changeSummary"), pydantic.Field(alias="changeSummary")
    ] = None
    definition: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Full transformed definition used by the bot runtime
    """

    flow_definition: typing_extensions.Annotated[
        typing.Optional[FlowDefinition], FieldMetadata(alias="flowDefinition"), pydantic.Field(alias="flowDefinition")
    ] = None
    notes: typing.Optional[str] = pydantic.Field(default=None)
    """
    Changelog notes for this version
    """

    published_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="publishedAt"),
        pydantic.Field(alias="publishedAt", description="Timestamp when this version was published"),
    ]
    """
    Timestamp when this version was published
    """

    published_by: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="publishedBy"),
        pydantic.Field(alias="publishedBy", description="User ID of the person who published this version"),
    ] = None
    """
    User ID of the person who published this version
    """

    published_by_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="publishedByName"),
        pydantic.Field(alias="publishedByName", description="Display name of the user who published this version"),
    ] = None
    """
    Display name of the user who published this version
    """

    version: str = pydantic.Field()
    """
    Semantic version string (X.Y.Z)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
