# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class HourlyVolume(UniversalBaseModel):
    """
    Hourly call volume data point
    """

    call_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="callCount"),
        pydantic.Field(alias="callCount", description="Number of calls in this hour"),
    ]
    """
    Number of calls in this hour
    """

    completed: int = pydantic.Field()
    """
    Completed calls in this hour
    """

    failed: int = pydantic.Field()
    """
    Failed calls in this hour
    """

    timestamp: dt.datetime = pydantic.Field()
    """
    Hour bucket timestamp (truncated to hour)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
