# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IceServerEntry(UniversalBaseModel):
    """
    ICE server entry for WebRTC NAT traversal
    """

    credential: typing.Optional[str] = pydantic.Field(default=None)
    """
    TURN credential (null for STUN servers)
    """

    urls: str = pydantic.Field()
    """
    STUN or TURN URL
    """

    username: typing.Optional[str] = pydantic.Field(default=None)
    """
    TURN username (null for STUN servers)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
