# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .invoice_status import InvoiceStatus


class InvoiceResponse(UniversalBaseModel):
    """
    Invoice response
    """

    amount_due: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="amountDue"),
        pydantic.Field(alias="amountDue", description="Total amount due in cents"),
    ]
    """
    Total amount due in cents
    """

    amount_paid: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="amountPaid"),
        pydantic.Field(alias="amountPaid", description="Amount already paid in cents"),
    ]
    """
    Amount already paid in cents
    """

    billing_reason: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="billingReason"),
        pydantic.Field(alias="billingReason", description="Reason for the invoice"),
    ] = None
    """
    Reason for the invoice
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the invoice was created"),
    ]
    """
    When the invoice was created
    """

    currency: str = pydantic.Field()
    """
    Currency code
    """

    due_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="dueDate"),
        pydantic.Field(alias="dueDate", description="When the invoice payment is due"),
    ] = None
    """
    When the invoice payment is due
    """

    hosted_invoice_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="hostedInvoiceUrl"),
        pydantic.Field(alias="hostedInvoiceUrl", description="URL to the hosted Stripe invoice page"),
    ] = None
    """
    URL to the hosted Stripe invoice page
    """

    id: str = pydantic.Field()
    """
    Unique invoice identifier
    """

    invoice_pdf_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="invoicePdfUrl"),
        pydantic.Field(alias="invoicePdfUrl", description="URL to download the invoice PDF"),
    ] = None
    """
    URL to download the invoice PDF
    """

    paid_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="paidAt"),
        pydantic.Field(alias="paidAt", description="When the invoice was paid"),
    ] = None
    """
    When the invoice was paid
    """

    period_end: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="periodEnd"),
        pydantic.Field(alias="periodEnd", description="End of the billing period"),
    ] = None
    """
    End of the billing period
    """

    period_start: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="periodStart"),
        pydantic.Field(alias="periodStart", description="Start of the billing period"),
    ] = None
    """
    Start of the billing period
    """

    status: InvoiceStatus = pydantic.Field()
    """
    Current invoice status
    """

    stripe_invoice_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="stripeInvoiceId"),
        pydantic.Field(alias="stripeInvoiceId", description="Stripe invoice identifier"),
    ]
    """
    Stripe invoice identifier
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
