# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class LanguageInfo(UniversalBaseModel):
    """
    Language information for API responses
    """

    code: str = pydantic.Field()
    """
    Language code (e.g., "en", "es")
    """

    name: str = pydantic.Field()
    """
    Display name in English (e.g., "English", "Spanish")
    """

    native_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="nativeName"),
        pydantic.Field(alias="nativeName", description='Native name (e.g., "English", "Espanol")'),
    ]
    """
    Native name (e.g., "English", "Espanol")
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
