# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class LatencyMetrics(UniversalBaseModel):
    """
    Latency performance metrics
    """

    avg_first_speech_ms: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="avgFirstSpeechMs"),
        pydantic.Field(
            alias="avgFirstSpeechMs",
            description="Average first speech latency in milliseconds (client connect to first bot audio)",
        ),
    ] = None
    """
    Average first speech latency in milliseconds (client connect to first bot audio)
    """

    p50first_speech_ms: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="p50FirstSpeechMs"),
        pydantic.Field(alias="p50FirstSpeechMs", description="Median first speech latency in milliseconds"),
    ] = None
    """
    Median first speech latency in milliseconds
    """

    p95first_speech_ms: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="p95FirstSpeechMs"),
        pydantic.Field(alias="p95FirstSpeechMs", description="95th percentile first speech latency"),
    ] = None
    """
    95th percentile first speech latency
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
