# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListMeta(UniversalBaseModel):
    """
    Pagination metadata for list responses
    """

    limit: int = pydantic.Field()
    """
    Maximum number of items returned per page
    """

    offset: int = pydantic.Field()
    """
    Number of items skipped from the beginning
    """

    total: int = pydantic.Field()
    """
    Total number of items matching the query
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
