# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .llm_model import LlmModel


class LlmProvider(UniversalBaseModel):
    """
    LLM provider with models and pricing
    """

    display_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="displayName"),
        pydantic.Field(alias="displayName", description='Display name (e.g., "OpenAI", "Anthropic")'),
    ]
    """
    Display name (e.g., "OpenAI", "Anthropic")
    """

    models: typing.List[LlmModel] = pydantic.Field()
    """
    Available models with pricing
    """

    provider: str = pydantic.Field()
    """
    Provider identifier (e.g., "openai", "anthropic")
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
