# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class MakeCallResponseQueued(UniversalBaseModel):
    """
    Call queued for later processing (202 Accepted)
    """

    estimated_wait_seconds: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="estimatedWaitSeconds"),
        pydantic.Field(alias="estimatedWaitSeconds", description="Estimated wait time before the call is processed"),
    ] = None
    """
    Estimated wait time before the call is processed
    """

    flow_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="flowId"),
        pydantic.Field(alias="flowId", description="Flow ID for the AI conversation"),
    ]
    """
    Flow ID for the AI conversation
    """

    from_number: typing_extensions.Annotated[
        str, FieldMetadata(alias="fromNumber"), pydantic.Field(alias="fromNumber", description="Caller phone number")
    ]
    """
    Caller phone number
    """

    position: int = pydantic.Field()
    """
    Position in the call queue (1-indexed)
    """

    queue_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="queueId"), pydantic.Field(alias="queueId", description="Queue entry identifier")
    ]
    """
    Queue entry identifier
    """

    to_number: typing_extensions.Annotated[
        str, FieldMetadata(alias="toNumber"), pydantic.Field(alias="toNumber", description="Destination phone number")
    ]
    """
    Destination phone number
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
