# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class MaxCallDurationSettings(UniversalBaseModel):
    """
    Hard call-duration cap settings for a flow.

    Omitting this block leaves the cap OFF. Sending it fully replaces the flow's cap config.
    """

    enabled: bool = pydantic.Field()
    """
    Whether the hard cap is enabled.
    """

    end_message: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="endMessage"),
        pydantic.Field(alias="endMessage", description="Spoken message before hanging up at the cap (max 1000 chars)."),
    ] = None
    """
    Spoken message before hanging up at the cap (max 1000 chars).
    """

    seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Cap in seconds; the bot ends the call once reached (30–14400).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
