# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .member_hours import MemberHours


class MemberHoursResponse(UniversalBaseModel):
    """
    A member's available hours.
    """

    hours: typing.Optional[MemberHours] = None
    member_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="memberId"),
        pydantic.Field(alias="memberId", description="Membership ID of the member in your organization"),
    ]
    """
    Membership ID of the member in your organization
    """

    user_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="userId"), pydantic.Field(alias="userId", description="User ID of the member")
    ]
    """
    User ID of the member
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
