# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MemberHoursRange(UniversalBaseModel):
    """
    A range of local time on one day. It never crosses midnight: for an
    overnight shift use two ranges on two days, e.g. `22:00`–`24:00` and
    `00:00`–`06:00`.
    """

    end: str = pydantic.Field()
    """
    End, `HH:MM` (00:01–24:00), exclusive; after `start` on the same day
    """

    start: str = pydantic.Field()
    """
    Start, `HH:MM` (00:00–23:59), inclusive
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
