# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PaginationMeta(UniversalBaseModel):
    """
    Pagination metadata in responses
    """

    limit: int = pydantic.Field()
    """
    Number of items in current response
    """

    offset: int = pydantic.Field()
    """
    Number of items skipped
    """

    total: int = pydantic.Field()
    """
    Total number of items available
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
