# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PromptReference(UniversalBaseModel):
    """
    Deprecated prompt wrapper, accepted for backwards compatibility. New
    definitions put the prompt inline in `AgentDefinition.agentPrompt`.
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    Inline content override (may contain {{handlebars}} expressions)
    """

    template_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="templateId"),
        pydantic.Field(
            alias="templateId",
            description="Prompt template UUID (references prompt_templates table).\nOptional — omit for inline-only prompts that don't reference a saved template.",
        ),
    ] = None
    """
    Prompt template UUID (references prompt_templates table).
    Optional — omit for inline-only prompts that don't reference a saved template.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
