# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .pricing_entry import PricingEntry
from .public_phone_number_pricing import PublicPhoneNumberPricing
from .recording_storage_pricing import RecordingStoragePricing


class PublicPricingResponse(UniversalBaseModel):
    """
    Public pricing response for telephony, phone numbers, and storage

    LLM/STT/TTS pricing is served by `/api/v1/models/*` with richer data
    (capabilities, languages, use-case filtering).
    """

    phone_numbers: typing_extensions.Annotated[
        PublicPhoneNumberPricing,
        FieldMetadata(alias="phoneNumbers"),
        pydantic.Field(alias="phoneNumbers", description="Phone number purchase and rental pricing"),
    ]
    """
    Phone number purchase and rental pricing
    """

    recording_storage: typing_extensions.Annotated[
        RecordingStoragePricing,
        FieldMetadata(alias="recordingStorage"),
        pydantic.Field(alias="recordingStorage", description="Recording storage pricing"),
    ]
    """
    Recording storage pricing
    """

    telephony: typing.List[PricingEntry] = pydantic.Field()
    """
    Telephony provider rates (per-minute pricing)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
