# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .rate_info import RateInfo


class PublicPhoneNumberPricing(UniversalBaseModel):
    """
    Phone number pricing (starting from cheapest)
    """

    note: str = pydantic.Field()
    """
    Additional context about phone number pricing
    """

    starting_from: typing_extensions.Annotated[
        RateInfo,
        FieldMetadata(alias="startingFrom"),
        pydantic.Field(alias="startingFrom", description="Lowest available monthly rate for a phone number"),
    ]
    """
    Lowest available monthly rate for a phone number
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
