# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RateInfo(UniversalBaseModel):
    """
    Rate amount with display string
    """

    display: str = pydantic.Field()
    """
    Formatted rate for display (e.g., "$0.0140")
    """

    microcents: int = pydantic.Field()
    """
    Rate in microcents (1 USD = 1,000,000 microcents)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
