# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .schedule_frequency import ScheduleFrequency
from .schedule_status import ScheduleStatus


class ScheduleResponse(UniversalBaseModel):
    """
    Schedule response
    """

    contact_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="contactId"),
        pydantic.Field(alias="contactId", description="Contact to call on each execution"),
    ]
    """
    Contact to call on each execution
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the schedule was created"),
    ]
    """
    When the schedule was created
    """

    cron_expression: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="cronExpression"),
        pydantic.Field(alias="cronExpression", description="Custom cron expression (when frequency is `custom_cron`)"),
    ] = None
    """
    Custom cron expression (when frequency is `custom_cron`)
    """

    day_of_month: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="dayOfMonth"),
        pydantic.Field(alias="dayOfMonth", description="Day of month (1-28)"),
    ] = None
    """
    Day of month (1-28)
    """

    days_of_week: typing_extensions.Annotated[
        typing.Optional[typing.List[int]],
        FieldMetadata(alias="daysOfWeek"),
        pydantic.Field(alias="daysOfWeek", description="Days of week (1=Monday through 7=Sunday)"),
    ] = None
    """
    Days of week (1=Monday through 7=Sunday)
    """

    end_date: typing_extensions.Annotated[
        typing.Optional[dt.date],
        FieldMetadata(alias="endDate"),
        pydantic.Field(alias="endDate", description="Date after which the schedule will not execute"),
    ] = None
    """
    Date after which the schedule will not execute
    """

    flow_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="flowId"),
        pydantic.Field(alias="flowId", description="Flow (conversation script) used for the call"),
    ]
    """
    Flow (conversation script) used for the call
    """

    flow_version: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="flowVersion"),
        pydantic.Field(alias="flowVersion", description="Pinned flow version at time of schedule creation"),
    ] = None
    """
    Pinned flow version at time of schedule creation
    """

    frequency: ScheduleFrequency = pydantic.Field()
    """
    How often the schedule repeats
    """

    from_phone_number: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="fromPhoneNumber"),
        pydantic.Field(alias="fromPhoneNumber", description="Caller ID phone number in E.164 format"),
    ]
    """
    Caller ID phone number in E.164 format
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the schedule
    """

    last_run_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="lastRunAt"),
        pydantic.Field(alias="lastRunAt", description="Last execution time in UTC"),
    ] = None
    """
    Last execution time in UTC
    """

    max_retries: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="maxRetries"),
        pydantic.Field(alias="maxRetries", description="Maximum retry attempts per execution"),
    ]
    """
    Maximum retry attempts per execution
    """

    max_runs: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="maxRuns"),
        pydantic.Field(alias="maxRuns", description="Maximum number of executions before auto-completing"),
    ] = None
    """
    Maximum number of executions before auto-completing
    """

    name: str = pydantic.Field()
    """
    Human-readable name for the schedule
    """

    next_run_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="nextRunAt"),
        pydantic.Field(alias="nextRunAt", description="Next scheduled execution time in UTC"),
    ] = None
    """
    Next scheduled execution time in UTC
    """

    provider_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="providerId"),
        pydantic.Field(alias="providerId", description="VoIP provider used for routing"),
    ]
    """
    VoIP provider used for routing
    """

    retry_delay_minutes: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="retryDelayMinutes"),
        pydantic.Field(alias="retryDelayMinutes", description="Minutes between retry attempts"),
    ]
    """
    Minutes between retry attempts
    """

    retry_on_failure: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="retryOnFailure"),
        pydantic.Field(alias="retryOnFailure", description="Whether failed calls are retried"),
    ]
    """
    Whether failed calls are retried
    """

    run_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="runCount"),
        pydantic.Field(alias="runCount", description="Number of times the schedule has executed so far"),
    ]
    """
    Number of times the schedule has executed so far
    """

    schedule_time: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="scheduleTime"),
        pydantic.Field(alias="scheduleTime", description="Time of day in HH:MM format"),
    ]
    """
    Time of day in HH:MM format
    """

    status: ScheduleStatus = pydantic.Field()
    """
    Current status of the schedule
    """

    timezone: str = pydantic.Field()
    """
    IANA timezone used for schedule_time interpretation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
