# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SttServiceDefinition(UniversalBaseModel):
    """
    STT service configuration

    Supports: deepgram, soniox, elevenlabs, cartesia.
    Use `language` for single-language providers, `languages` for Soniox multi-language.
    """

    keywords: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Keyword boosting terms
    """

    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display label for UI
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Single language code (Deepgram, ElevenLabs, Cartesia, AssemblyAI, Whisper)
    """

    languages: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Language hints array for Soniox multi-language detection
    """

    model: str = pydantic.Field()
    """
    Model identifier
    """

    provider: str = pydantic.Field()
    """
    Provider identifier
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
