# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .ice_server_entry import IceServerEntry


class TransferOfferWebRtcAnswer(UniversalBaseModel):
    """
    WebRTC join: the SDP answer plus the ICE servers to keep using
    (short-lived TURN credentials).
    """

    call_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="callId"), pydantic.Field(alias="callId", description="Call joined")
    ]
    """
    Call joined
    """

    expires_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="expiresAt"),
        pydantic.Field(alias="expiresAt", description="The TURN credentials stop working after this time"),
    ]
    """
    The TURN credentials stop working after this time
    """

    ice_servers: typing_extensions.Annotated[
        typing.List[IceServerEntry],
        FieldMetadata(alias="iceServers"),
        pydantic.Field(alias="iceServers", description="ICE servers for the connection"),
    ]
    """
    ICE servers for the connection
    """

    sdp_answer: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="sdpAnswer"),
        pydantic.Field(alias="sdpAnswer", description="SDP answer to apply to your peer connection"),
    ]
    """
    SDP answer to apply to your peer connection
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
