# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .pagination_meta import PaginationMeta
from .transfer_destination import TransferDestination


class TransferDestinationListResponse(UniversalBaseModel):
    """
    Page of transfer destinations
    """

    destinations: typing.List[TransferDestination] = pydantic.Field()
    """
    Items on this page
    """

    meta: PaginationMeta = pydantic.Field()
    """
    Pagination metadata
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
