# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .transcript_message_metrics import TranscriptMessageMetrics
from .transcript_speaker import TranscriptSpeaker


class TranscriptMessage(UniversalBaseModel):
    """
    Structured transcript message representing one speech segment
    """

    content: str = pydantic.Field()
    """
    Transcribed text content
    """

    duration_ms: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="durationMs"),
        pydantic.Field(alias="durationMs", description="Duration of this speech segment in milliseconds"),
    ] = None
    """
    Duration of this speech segment in milliseconds
    """

    llm_model: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="llmModel"),
        pydantic.Field(alias="llmModel", description="LLM model used for this message (assistant only)"),
    ] = None
    """
    LLM model used for this message (assistant only)
    """

    metrics: typing.Optional[TranscriptMessageMetrics] = None
    speaker: TranscriptSpeaker = pydantic.Field()
    """
    Who spoke this message
    """

    speaker_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="speakerName"),
        pydantic.Field(alias="speakerName", description="Display name of the speaker"),
    ] = None
    """
    Display name of the speaker
    """

    timestamp_ms: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="timestampMs"),
        pydantic.Field(alias="timestampMs", description="When this message occurred (milliseconds since call start)"),
    ]
    """
    When this message occurred (milliseconds since call start)
    """

    tts_model: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ttsModel"),
        pydantic.Field(alias="ttsModel", description="TTS model used for this message (assistant only)"),
    ] = None
    """
    TTS model used for this message (assistant only)
    """

    turn_number: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="turnNumber"),
        pydantic.Field(alias="turnNumber", description="Conversation turn number this message belongs to (1-based)"),
    ] = None
    """
    Conversation turn number this message belongs to (1-based)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
