# This file was auto-generated by Fern from our API Definition.

import typing

TransactionType = typing.Union[
    typing.Literal[
        "subscription_grant",
        "purchase",
        "usage",
        "refund",
        "adjustment",
        "expiration",
        "dispute_hold",
        "dispute_release",
        "dispute_loss",
        "refund_deduction",
    ],
    typing.Any,
]
