# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class TransitionDefinition(UniversalBaseModel):
    """
    Agent transition definition. Defines a handoff from one agent to another, triggered by keywords in the conversation. Exposed to the LLM as a tool at runtime.
    """

    keywords: typing.Optional[str] = pydantic.Field(default=None)
    """
    Keywords/description that trigger this transition
    """

    target_agent_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="targetAgentId"),
        pydantic.Field(alias="targetAgentId", description="Target agent node ID"),
    ]
    """
    Target agent node ID
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
