# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class TtsPricing(UniversalBaseModel):
    """
    TTS pricing from database
    """

    rate_per1k_chars_display: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="ratePer1kCharsDisplay"),
        pydantic.Field(alias="ratePer1kCharsDisplay", description='Human-readable rate (e.g., "$0.10")'),
    ]
    """
    Human-readable rate (e.g., "$0.10")
    """

    rate_per1k_chars_microcents: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="ratePer1kCharsMicrocents"),
        pydantic.Field(
            alias="ratePer1kCharsMicrocents",
            description="Rate per 1000 characters in microcents (1 cent = 10,000 microcents)",
        ),
    ]
    """
    Rate per 1000 characters in microcents (1 cent = 10,000 microcents)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
