# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class TtsServiceDefinition(UniversalBaseModel):
    """
    TTS service configuration

    Supports: elevenlabs, cartesia.
    Provider-specific fields are flattened — only relevant fields are set per provider.
    """

    emotion: typing.Optional[str] = pydantic.Field(default=None)
    """
    Voice emotion preset (Cartesia Sonic v3)
    """

    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display label for UI
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Voice language for localization (Cartesia)
    """

    model: str = pydantic.Field()
    """
    Model identifier
    """

    provider: str = pydantic.Field()
    """
    Provider identifier
    """

    similarity: typing.Optional[float] = pydantic.Field(default=None)
    """
    Voice similarity boost (0.0 - 1.0, ElevenLabs)
    """

    speaker_boost: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="speakerBoost"),
        pydantic.Field(alias="speakerBoost", description="Speaker boost (ElevenLabs)"),
    ] = None
    """
    Speaker boost (ElevenLabs)
    """

    speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speech speed multiplier (Cartesia Sonic v3)
    """

    stability: typing.Optional[float] = pydantic.Field(default=None)
    """
    Voice stability (0.0 - 1.0, ElevenLabs)
    """

    style: typing.Optional[float] = pydantic.Field(default=None)
    """
    Voice style (0.0 - 1.0, ElevenLabs)
    """

    voice_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="voiceId"), pydantic.Field(alias="voiceId", description="Voice identifier")
    ]
    """
    Voice identifier
    """

    voice_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="voiceName"),
        pydantic.Field(alias="voiceName", description="Cached voice display name"),
    ] = None
    """
    Cached voice display name
    """

    volume: typing.Optional[float] = pydantic.Field(default=None)
    """
    Audio volume level (Cartesia Sonic v3)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
