# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .language_info import LanguageInfo
from .tts_capabilities import TtsCapabilities
from .tts_pricing import TtsPricing


class TtsModel(UniversalBaseModel):
    """
    TTS model with pricing information
    """

    capabilities: TtsCapabilities = pydantic.Field()
    """
    Model capabilities
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Model description
    """

    languages: typing.List[LanguageInfo] = pydantic.Field()
    """
    Supported languages
    """

    model_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="modelId"),
        pydantic.Field(alias="modelId", description='Model identifier (e.g., "eleven_turbo_v2_5")'),
    ]
    """
    Model identifier (e.g., "eleven_turbo_v2_5")
    """

    name: str = pydantic.Field()
    """
    Display name (e.g., "Turbo v2.5")
    """

    pricing: typing.Optional[TtsPricing] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
