# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .field_error import FieldError
from .transformation_summary import TransformationSummary


class ValidationResponse(UniversalBaseModel):
    """
    Validation success response (200 OK)

    Validation failures return ApiError with 400/422 status.
    """

    transformation_summary: typing_extensions.Annotated[
        typing.Optional[TransformationSummary],
        FieldMetadata(alias="transformationSummary"),
        pydantic.Field(alias="transformationSummary"),
    ] = None
    warnings: typing.Optional[typing.List[FieldError]] = pydantic.Field(default=None)
    """
    Non-fatal validation warnings (omitted when empty)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
