# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class VoiceDto(UniversalBaseModel):
    """
    A TTS voice.
    """

    category: typing.Optional[str] = pydantic.Field(default=None)
    """
    Voice category (premade, cloned, generated, professional)
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Voice description
    """

    is_legacy: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isLegacy"),
        pydantic.Field(alias="isLegacy", description="True for voices no longer recommended for new flows."),
    ]
    """
    True for voices no longer recommended for new flows.
    """

    labels: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Labels/tags (e.g., gender, accent)
    """

    name: str = pydantic.Field()
    """
    Display name
    """

    preview_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="previewUrl"),
        pydantic.Field(alias="previewUrl", description="Preview audio URL"),
    ] = None
    """
    Preview audio URL
    """

    public_owner_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="publicOwnerId"),
        pydantic.Field(
            alias="publicOwnerId",
            description="Public owner id — present only for shared-library voices; required to\nadd the voice to the account before it can be used for TTS.",
        ),
    ] = None
    """
    Public owner id — present only for shared-library voices; required to
    add the voice to the account before it can be used for TTS.
    """

    recommended_model_ids: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="recommendedModelIds"),
        pydantic.Field(alias="recommendedModelIds", description="Recommended model IDs for this voice"),
    ]
    """
    Recommended model IDs for this voice
    """

    voice_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="voiceId"), pydantic.Field(alias="voiceId", description="Unique voice identifier")
    ]
    """
    Unique voice identifier
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
