# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.call_direction import CallDirection
from ..types.call_insights import CallInsights
from ..types.call_list_response import CallListResponse
from ..types.call_provider_type import CallProviderType
from ..types.call_response import CallResponse
from ..types.call_source import CallSource
from ..types.call_status import CallStatus
from ..types.call_transcript_response import CallTranscriptResponse
from ..types.make_call_response import MakeCallResponse
from ..types.recording_url_response import RecordingUrlResponse
from .raw_client import AsyncRawCallsClient, RawCallsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CallsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCallsClient
        """
        return self._raw_client

    def make_call(
        self,
        *,
        flow_id: str,
        from_number: str,
        provider_id: str,
        to_number: str,
        campaign_contact_id: typing.Optional[str] = OMIT,
        campaign_id: typing.Optional[str] = OMIT,
        contact_id: typing.Optional[str] = OMIT,
        flow_version: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        source: typing.Optional[CallSource] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MakeCallResponse:
        """
        POST /api/v1/calls

        SECURITY: Verifies account access, phone ownership, provider ownership, flow ownership

        Returns:
        - 201 Created: Call initiated immediately (capacity available)
        - 202 Accepted: Call queued for later processing (at capacity/rate limited)

        Parameters
        ----------
        flow_id : str
            Flow ID to use for the AI conversation

        from_number : str
            Caller phone number in E.164 format, must be owned by the account

        provider_id : str
            Provider ID to route the call through

        to_number : str
            Destination phone number in E.164 format (emergency numbers blocked)

        campaign_contact_id : typing.Optional[str]
            Campaign contact ID for per-contact status tracking

        campaign_id : typing.Optional[str]
            Campaign ID if this call is part of a bulk campaign

        contact_id : typing.Optional[str]
            Contact ID to associate with this call

        flow_version : typing.Optional[str]
            Flow version to use, defaults to current published version

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Additional metadata to attach to the call

        source : typing.Optional[CallSource]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MakeCallResponse
            Call initiated or queued

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.calls.make_call(
            flow_id="550e8400-e29b-41d4-a716-446655440000",
            from_number="+15559876543",
            provider_id="550e8400-e29b-41d4-a716-446655440000",
            to_number="+15551234567",
        )
        """
        _response = self._raw_client.make_call(
            flow_id=flow_id,
            from_number=from_number,
            provider_id=provider_id,
            to_number=to_number,
            campaign_contact_id=campaign_contact_id,
            campaign_id=campaign_id,
            contact_id=contact_id,
            flow_version=flow_version,
            metadata=metadata,
            source=source,
            request_options=request_options,
        )
        return _response.data

    def get_active_calls(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[CallResponse, CallListResponse]:
        """
        GET /api/v1/calls/active

        Parameters
        ----------
        limit : typing.Optional[int]
            Max items to return (1-100, default 10)

        offset : typing.Optional[int]
            Items to skip (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[CallResponse, CallListResponse]
            Active calls

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        response = client.calls.get_active_calls()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.get_active_calls(limit=limit, offset=offset, request_options=request_options)

    def get_call_history(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        start_date: typing.Optional[dt.datetime] = None,
        end_date: typing.Optional[dt.datetime] = None,
        status: typing.Optional[CallStatus] = None,
        direction: typing.Optional[CallDirection] = None,
        source: typing.Optional[CallSource] = None,
        phone_number: typing.Optional[str] = None,
        is_lead: typing.Optional[bool] = None,
        flow_id: typing.Optional[str] = None,
        contact_id: typing.Optional[str] = None,
        schedule_id: typing.Optional[str] = None,
        campaign_id: typing.Optional[str] = None,
        provider_type: typing.Optional[CallProviderType] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[CallResponse, CallListResponse]:
        """
        GET /api/v1/calls/history

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return (default: 20, max: 100)

        offset : typing.Optional[int]
            Number of items to skip for pagination (default: 0)

        start_date : typing.Optional[dt.datetime]
            Only include calls after this timestamp (inclusive)

        end_date : typing.Optional[dt.datetime]
            Only include calls before this timestamp (inclusive)

        status : typing.Optional[CallStatus]
            Filter by call status

        direction : typing.Optional[CallDirection]
            Filter by call direction

        source : typing.Optional[CallSource]
            Filter by call source (direct, scheduled, campaign)

        phone_number : typing.Optional[str]
            Filter by phone number — matches either the from or to number (E.164)

        is_lead : typing.Optional[bool]
            Filter by whether the call was triggered by a Meta lead form (true = lead-driven only)

        flow_id : typing.Optional[str]
            Filter by flow ID

        contact_id : typing.Optional[str]
            Filter by contact ID

        schedule_id : typing.Optional[str]
            Filter by schedule ID (for scheduled calls)

        campaign_id : typing.Optional[str]
            Filter by campaign ID (for campaign calls)

        provider_type : typing.Optional[CallProviderType]
            Filter by telephony provider type (channel)

        search : typing.Optional[str]
            Free-text search across the contact name and the raw from/to phone
            numbers (case-insensitive substring). Matches calls to/from numbers that
            were never saved as contacts.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[CallResponse, CallListResponse]
            Call history

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        response = client.calls.get_call_history()
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.get_call_history(
            limit=limit,
            offset=offset,
            start_date=start_date,
            end_date=end_date,
            status=status,
            direction=direction,
            source=source,
            phone_number=phone_number,
            is_lead=is_lead,
            flow_id=flow_id,
            contact_id=contact_id,
            schedule_id=schedule_id,
            campaign_id=campaign_id,
            provider_type=provider_type,
            search=search,
            request_options=request_options,
        )

    def get_call_details(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CallResponse:
        """
        GET /api/v1/calls/:callId

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallResponse
            Call details

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.calls.get_call_details(
            call_id="callId",
        )
        """
        _response = self._raw_client.get_call_details(call_id, request_options=request_options)
        return _response.data

    def analyze_call(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[CallInsights]:
        """
        POST /api/v1/calls/:callId/analyze

        Generates AI-powered insights from the call transcript:
        - Summary (2-3 sentences)
        - Sentiment analysis (positive/neutral/negative + confidence)
        - Detected intents
        - Key topics discussed
        - Action items
        - Call outcome

        This endpoint is always available regardless of account auto-analysis settings.
        Can be used to:
        - Analyze calls that weren't auto-analyzed
        - Re-analyze calls with updated AI model

        Requires the call to be in a terminal state (COMPLETED/FAILED/etc.)
        and have a transcript available.

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[CallInsights]
            AI-powered call analysis with insights

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.calls.analyze_call(
            call_id="callId",
        )
        """
        _response = self._raw_client.analyze_call(call_id, request_options=request_options)
        return _response.data

    def get_call_recording(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RecordingUrlResponse:
        """
        Returns a time-limited presigned URL for recording playback. Fetch the
        audio directly from that URL.

        Requires the call to belong to the account and to have
        `recordingStatus = ready`; recording must be enabled for the account.

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordingUrlResponse
            Presigned URL for call recording playback

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.calls.get_call_recording(
            call_id="callId",
        )
        """
        _response = self._raw_client.get_call_recording(call_id, request_options=request_options)
        return _response.data

    def delete_call_recording(self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        DELETE /api/v1/calls/:callId/recording → 204

        Charges for actual storage duration before deletion (billing at lifecycle end).
        Uses idempotency key to prevent double-charging if racing with retention job.

        SECURITY: Verifies account access, call ownership.

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.calls.delete_call_recording(
            call_id="callId",
        )
        """
        _response = self._raw_client.delete_call_recording(call_id, request_options=request_options)
        return _response.data

    def get_call_transcript(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CallTranscriptResponse:
        """
        GET /api/v1/calls/:callId/transcript

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallTranscriptResponse
            Call transcript

        Examples
        --------
        from talkif import Talkif

        client = Talkif(
            token="YOUR_TOKEN",
        )
        client.calls.get_call_transcript(
            call_id="callId",
        )
        """
        _response = self._raw_client.get_call_transcript(call_id, request_options=request_options)
        return _response.data


class AsyncCallsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCallsClient
        """
        return self._raw_client

    async def make_call(
        self,
        *,
        flow_id: str,
        from_number: str,
        provider_id: str,
        to_number: str,
        campaign_contact_id: typing.Optional[str] = OMIT,
        campaign_id: typing.Optional[str] = OMIT,
        contact_id: typing.Optional[str] = OMIT,
        flow_version: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        source: typing.Optional[CallSource] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MakeCallResponse:
        """
        POST /api/v1/calls

        SECURITY: Verifies account access, phone ownership, provider ownership, flow ownership

        Returns:
        - 201 Created: Call initiated immediately (capacity available)
        - 202 Accepted: Call queued for later processing (at capacity/rate limited)

        Parameters
        ----------
        flow_id : str
            Flow ID to use for the AI conversation

        from_number : str
            Caller phone number in E.164 format, must be owned by the account

        provider_id : str
            Provider ID to route the call through

        to_number : str
            Destination phone number in E.164 format (emergency numbers blocked)

        campaign_contact_id : typing.Optional[str]
            Campaign contact ID for per-contact status tracking

        campaign_id : typing.Optional[str]
            Campaign ID if this call is part of a bulk campaign

        contact_id : typing.Optional[str]
            Contact ID to associate with this call

        flow_version : typing.Optional[str]
            Flow version to use, defaults to current published version

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Additional metadata to attach to the call

        source : typing.Optional[CallSource]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MakeCallResponse
            Call initiated or queued

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.make_call(
                flow_id="550e8400-e29b-41d4-a716-446655440000",
                from_number="+15559876543",
                provider_id="550e8400-e29b-41d4-a716-446655440000",
                to_number="+15551234567",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.make_call(
            flow_id=flow_id,
            from_number=from_number,
            provider_id=provider_id,
            to_number=to_number,
            campaign_contact_id=campaign_contact_id,
            campaign_id=campaign_id,
            contact_id=contact_id,
            flow_version=flow_version,
            metadata=metadata,
            source=source,
            request_options=request_options,
        )
        return _response.data

    async def get_active_calls(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[CallResponse, CallListResponse]:
        """
        GET /api/v1/calls/active

        Parameters
        ----------
        limit : typing.Optional[int]
            Max items to return (1-100, default 10)

        offset : typing.Optional[int]
            Items to skip (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[CallResponse, CallListResponse]
            Active calls

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.calls.get_active_calls()
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.get_active_calls(limit=limit, offset=offset, request_options=request_options)

    async def get_call_history(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        start_date: typing.Optional[dt.datetime] = None,
        end_date: typing.Optional[dt.datetime] = None,
        status: typing.Optional[CallStatus] = None,
        direction: typing.Optional[CallDirection] = None,
        source: typing.Optional[CallSource] = None,
        phone_number: typing.Optional[str] = None,
        is_lead: typing.Optional[bool] = None,
        flow_id: typing.Optional[str] = None,
        contact_id: typing.Optional[str] = None,
        schedule_id: typing.Optional[str] = None,
        campaign_id: typing.Optional[str] = None,
        provider_type: typing.Optional[CallProviderType] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[CallResponse, CallListResponse]:
        """
        GET /api/v1/calls/history

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of items to return (default: 20, max: 100)

        offset : typing.Optional[int]
            Number of items to skip for pagination (default: 0)

        start_date : typing.Optional[dt.datetime]
            Only include calls after this timestamp (inclusive)

        end_date : typing.Optional[dt.datetime]
            Only include calls before this timestamp (inclusive)

        status : typing.Optional[CallStatus]
            Filter by call status

        direction : typing.Optional[CallDirection]
            Filter by call direction

        source : typing.Optional[CallSource]
            Filter by call source (direct, scheduled, campaign)

        phone_number : typing.Optional[str]
            Filter by phone number — matches either the from or to number (E.164)

        is_lead : typing.Optional[bool]
            Filter by whether the call was triggered by a Meta lead form (true = lead-driven only)

        flow_id : typing.Optional[str]
            Filter by flow ID

        contact_id : typing.Optional[str]
            Filter by contact ID

        schedule_id : typing.Optional[str]
            Filter by schedule ID (for scheduled calls)

        campaign_id : typing.Optional[str]
            Filter by campaign ID (for campaign calls)

        provider_type : typing.Optional[CallProviderType]
            Filter by telephony provider type (channel)

        search : typing.Optional[str]
            Free-text search across the contact name and the raw from/to phone
            numbers (case-insensitive substring). Matches calls to/from numbers that
            were never saved as contacts.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[CallResponse, CallListResponse]
            Call history

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.calls.get_call_history()
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.get_call_history(
            limit=limit,
            offset=offset,
            start_date=start_date,
            end_date=end_date,
            status=status,
            direction=direction,
            source=source,
            phone_number=phone_number,
            is_lead=is_lead,
            flow_id=flow_id,
            contact_id=contact_id,
            schedule_id=schedule_id,
            campaign_id=campaign_id,
            provider_type=provider_type,
            search=search,
            request_options=request_options,
        )

    async def get_call_details(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CallResponse:
        """
        GET /api/v1/calls/:callId

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallResponse
            Call details

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.get_call_details(
                call_id="callId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_call_details(call_id, request_options=request_options)
        return _response.data

    async def analyze_call(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[CallInsights]:
        """
        POST /api/v1/calls/:callId/analyze

        Generates AI-powered insights from the call transcript:
        - Summary (2-3 sentences)
        - Sentiment analysis (positive/neutral/negative + confidence)
        - Detected intents
        - Key topics discussed
        - Action items
        - Call outcome

        This endpoint is always available regardless of account auto-analysis settings.
        Can be used to:
        - Analyze calls that weren't auto-analyzed
        - Re-analyze calls with updated AI model

        Requires the call to be in a terminal state (COMPLETED/FAILED/etc.)
        and have a transcript available.

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[CallInsights]
            AI-powered call analysis with insights

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.analyze_call(
                call_id="callId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.analyze_call(call_id, request_options=request_options)
        return _response.data

    async def get_call_recording(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RecordingUrlResponse:
        """
        Returns a time-limited presigned URL for recording playback. Fetch the
        audio directly from that URL.

        Requires the call to belong to the account and to have
        `recordingStatus = ready`; recording must be enabled for the account.

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordingUrlResponse
            Presigned URL for call recording playback

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.get_call_recording(
                call_id="callId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_call_recording(call_id, request_options=request_options)
        return _response.data

    async def delete_call_recording(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        DELETE /api/v1/calls/:callId/recording → 204

        Charges for actual storage duration before deletion (billing at lifecycle end).
        Uses idempotency key to prevent double-charging if racing with retention job.

        SECURITY: Verifies account access, call ownership.

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.delete_call_recording(
                call_id="callId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_call_recording(call_id, request_options=request_options)
        return _response.data

    async def get_call_transcript(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CallTranscriptResponse:
        """
        GET /api/v1/calls/:callId/transcript

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallTranscriptResponse
            Call transcript

        Examples
        --------
        import asyncio

        from talkif import AsyncTalkif

        client = AsyncTalkif(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.get_call_transcript(
                call_id="callId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_call_transcript(call_id, request_options=request_options)
        return _response.data
